<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <ProjectReference Include="..\Jornada.Pipeline.Coordination\Jornada.Pipeline.Coordination.csproj" />
    <ProjectReference Include="..\Jornada.Contracts\Jornada.Contracts.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>
</Project>
