<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Jornada.Contracts\Jornada.Contracts.csproj" />
    <ProjectReference Include="..\Jornada.Ingestion\Jornada.Ingestion.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\data\reference\ibge-nomes-2022\**\*"
          Link="data\reference\ibge-nomes-2022\%(RecursiveDir)%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="Never" />
  </ItemGroup>
</Project>
