using System.Globalization;
using System.Text;
#pragma warning disable CA1305 // Markdown de evidência usa formatos explícitos nos valores numéricos e temporais.
namespace Jornada.Ensaio;
public static class CheckpointDiff
{
    private static bool EhMetrica(string coluna){var c=coluna.ToLowerInvariant();return c is "n" or "pares" or "pessoas" or "entregas" or "avaliados" or "pares_possiveis" or "pessoas_multi_gestor" or "tamanho_amostra_referencia" or "valor"||c.StartsWith("pct_",StringComparison.Ordinal)||c.StartsWith("ppv",StringComparison.Ordinal)||c.StartsWith("sensibilidade",StringComparison.Ordinal);}
    public static string Gerar(Checkpoint antes,Checkpoint depois){var sb=new StringBuilder();sb.AppendLine($"# Diff  `{antes.Etapa}` → `{depois.Etapa}`").AppendLine();sb.AppendLine(depois.Descricao).AppendLine();var mudou=false;foreach(var bd in depois.Blocos){if(bd.Erro is not null)continue;var ba=antes.Blocos.FirstOrDefault(x=>x.Chave==bd.Chave);if(ba is null||ba.Erro is not null||!ba.Colunas.SequenceEqual(bd.Colunas))continue;var idxChave=bd.Colunas.Select((c,i)=>(c,i)).Where(x=>!EhMetrica(x.c)).Select(x=>x.i).ToArray();var idxMetrica=bd.Colunas.Select((c,i)=>(c,i)).Where(x=>EhMetrica(x.c)).Select(x=>x.i).ToArray();if(idxMetrica.Length==0)continue;static string Chave(IReadOnlyList<string?> l,int[] idx)=>idx.Length==0?"(total)":string.Join(" / ",idx.Select(i=>l[i]??""));var mapaA=ba.Linhas.ToDictionary(l=>Chave(l,idxChave),l=>l);var mapaD=bd.Linhas.ToDictionary(l=>Chave(l,idxChave),l=>l);var linhas=new List<string>();foreach(var k in mapaA.Keys.Union(mapaD.Keys).OrderBy(x=>x,StringComparer.Ordinal)){mapaA.TryGetValue(k,out var la);mapaD.TryGetValue(k,out var ld);foreach(var i in idxMetrica){var va=la is null?null:la[i];var vd=ld is null?null:ld[i];if(va==vd)continue;var delta="";if(double.TryParse(va??"0",NumberStyles.Any,CultureInfo.InvariantCulture,out var x)&&double.TryParse(vd??"0",NumberStyles.Any,CultureInfo.InvariantCulture,out var y))delta=(y-x).ToString("+0.####;-0.####;0",CultureInfo.InvariantCulture);linhas.Add($"| {k} | {bd.Colunas[i]} | {va??"—"} | {vd??"—"} | {delta} |");}}if(linhas.Count==0)continue;mudou=true;sb.AppendLine($"## {bd.Descricao}").AppendLine("| chave | métrica | antes | depois | Δ |").AppendLine("|---|---|---|---|---|");foreach(var l in linhas)sb.AppendLine(l);sb.AppendLine();}if(!mudou)sb.AppendLine("_nenhuma diferença nos blocos comparáveis_").AppendLine();foreach(var o in Expectativas(depois))sb.AppendLine($"- {o}");return sb.ToString();}
    private static IEnumerable<string> Expectativas(Checkpoint cp){double? M(string bloco,string coluna){var b=cp.Blocos.FirstOrDefault(x=>x.Chave==bloco);if(b?.Erro is not null||b is null||b.Linhas.Count==0)return null;var i=b.Colunas.ToList().IndexOf(coluna);return i>=0&&double.TryParse(b.Linhas[0][i],NumberStyles.Any,CultureInfo.InvariantCulture,out var v)?v:null;}var pares=M("pares_m","pares_possiveis");if(pares is not null)yield return pares>0?$"**Pares m inter-Gestor disponíveis: {pares:0}.** Há evidência candidata; a geração ainda depende do limiar mínimo de suficiência configurado.":"Pares m inter-Gestor = 0. O Calibrador deve falhar fechado por insuficiência de evidência.";var nome=M("independencia","pct_nome_exato");if(nome is not null)yield return nome>=95?$"**Concordância exata de nome em {nome:0.0}%** — indício forte de dependência/cópia entre fontes; investigar antes de tratar a evidência como independente.":$"Concordância exata de nome em {nome:0.0}% — indicador diagnóstico de independência das fontes.";}
}
#pragma warning restore CA1305
