using System.Globalization;
using System.Text;

namespace Jornada.Ensaio;

public static class EnsaioReport
{
    public static string Gerar(IReadOnlyList<Checkpoint> cps,IReadOnlyList<string> eventos)
    {
        var sb=new StringBuilder(); sb.AppendLine("# Relatório do Ensaio Progressivo da Jornada\n").AppendLine($"Gerado em: {DateTimeOffset.Now:O}  ").AppendLine($"Baseline: `{cps.LastOrDefault()?.BaselineSha??"(não informado)"}`  ").AppendLine($"Checkpoints coletados: **{cps.Count}**\n");
        if(cps.Count==0)return sb.AppendLine("Nenhum checkpoint foi coletado; não há evidência suficiente para interpretar o ensaio.").ToString();
        sb.AppendLine("## Resumo executivo\n"); foreach(var x in Resumo(cps,eventos))sb.AppendLine($"- {x}");
        sb.AppendLine("\n## Linha do tempo e interpretação\n");
        for(var i=0;i<cps.Count;i++){var cp=cps[i];sb.AppendLine($"### {cp.Etapa} — {cp.Descricao}\n").AppendLine($"Capturado em `{cp.CapturadoEm:O}`.\n");foreach(var x in Interpretar(cp))sb.AppendLine($"- {x}");if(i>0){sb.AppendLine("\n**Mudanças desde o checkpoint anterior:**\n");foreach(var x in CheckpointDiff.Gerar(cps[i-1],cp).Split('\n').Where(x=>x.StartsWith("- ")))sb.AppendLine(x);}sb.AppendLine();}
        sb.AppendLine("## Eventos operacionais\n");if(eventos.Count==0)sb.AppendLine("_Nenhuma falha ou evento adicional foi registrado._");else foreach(var x in eventos)sb.AppendLine($"- {x}");
        sb.AppendLine("\n## Limites da interpretação\n").AppendLine("Este relatório interpreta evidências observadas no banco e nos processos do ensaio; ausência de evidência não é evidência de ausência. Blocos indisponíveis são lacunas de observabilidade, não valor zero. Completude de dados não mede acurácia de ligação. A qualidade de ligação só deve ser afirmada com amostra de referência suficiente e PPV/sensibilidade com intervalos de confiança. Um modelo em RASCUNHO demonstra geração de parâmetros, não validação nem ativação.");return sb.ToString();
    }
    private static IEnumerable<string> Resumo(IReadOnlyList<Checkpoint> cps,IReadOnlyList<string> eventos){var f=cps[^1];var falhas=eventos.Count(x=>x.Contains("FALHA",StringComparison.OrdinalIgnoreCase));yield return falhas==0?"O orquestrador não registrou falhas de etapa.":$"Foram registradas **{falhas} falhas de etapa**; a linha do tempo deve ser examinada antes de considerar o ensaio aprovado.";var obs=Valor(f,"volumes","n","camada","silver.pessoa_observacao");var gold=Valor(f,"volumes","n","camada","gold.pessoa");if(obs is not null&&gold is not null)yield return $"Estado final: **{obs:0} observações Silver** e **{gold:0} pessoas Gold**. A diferença é indicador operacional de convergência, não medida de acurácia.";var pares=Numero(f,"pares_m","pares_possiveis");if(pares is not null)yield return pares>0?$"Existem **{pares:0} pares candidatos m inter-Gestor**; a geração ainda depende do mínimo de suficiência configurado.":"Não existem pares m inter-Gestor; o calibrador deve permanecer fail-closed.";var b=f.Blocos.FirstOrDefault(x=>x.Chave=="modelos");if(b is {Erro:null,Linhas.Count:>0}){var s=Campo(b,b.Linhas[0],"status");if(s is not null)yield return $"Modelo mais recente: **{s}**. "+(s.Equals("RASCUNHO",StringComparison.OrdinalIgnoreCase)?"Geração não implica validação/ativação.":s.Equals("FALHOU",StringComparison.OrdinalIgnoreCase)?"O fail-closed ficou materializado no estado persistido.":"O estado deve ser confrontado com a política de publicação.");}var erros=f.Blocos.Where(x=>x.Erro is not null).Select(x=>x.Chave).ToArray();if(erros.Length>0)yield return $"Há **{erros.Length} blocos indisponíveis** no checkpoint final: {string.Join(", ",erros)}. Nenhum foi interpretado como zero.";}
    private static IEnumerable<string> Interpretar(Checkpoint cp){var obs=Valor(cp,"volumes","n","camada","silver.pessoa_observacao");var gold=Valor(cp,"volumes","n","camada","gold.pessoa");if(obs is not null&&gold is not null)yield return $"Volume: {obs:0} observações Silver para {gold:0} pessoas Gold.";var cpf=Numero(cp,"gold_preenchimento","pct_cpf");if(cpf is not null)yield return $"Completude de CPF na Gold: {cpf:0.##}%. Completude mede disponibilidade de evidência, não correção do vínculo.";var pares=Numero(cp,"pares_m","pares_possiveis");if(pares is not null)yield return pares==0?"Sem pares determinísticos entre Gestores: é correto impedir calibração m por insuficiência de evidência independente.":$"{pares:0} pares determinísticos potenciais entre Gestores; ainda é necessário atingir o mínimo configurado e preservar independência contra leakage.";var ex=Numero(cp,"independencia","pct_nome_exato");if(ex is not null)yield return ex>=95?$"Concordância exata intra-Gestor de {ex:0.##}% é muito alta e merece investigação de dependência/cópia entre fontes.":$"Concordância exata intra-Gestor de {ex:0.##}% é indicador diagnóstico de independência, não score de linkage.";var q=cp.Blocos.FirstOrDefault(x=>x.Chave=="qualidade_estimada");if(q?.Erro is not null)yield return "PPV/sensibilidade não puderam ser observados; não se deve inferir acurácia de ligação.";else if(q is {Linhas.Count:>0})yield return "Há estimativas calibradas de PPV/sensibilidade; esses valores e seus intervalos de confiança são a evidência apropriada para discutir erro de ligação.";foreach(var b in cp.Blocos.Where(x=>x.Erro is not null))yield return $"Bloco `{b.Chave}` indisponível: {b.Erro}. É lacuna de observabilidade neste ensaio.";}
    private static double? Numero(Checkpoint cp,string bloco,string coluna){var b=cp.Blocos.FirstOrDefault(x=>x.Chave==bloco);if(b?.Erro is not null||b is null||b.Linhas.Count==0)return null;var i=b.Colunas.ToList().IndexOf(coluna);return i>=0&&double.TryParse(b.Linhas[0][i],NumberStyles.Any,CultureInfo.InvariantCulture,out var v)?v:null;}
    private static double? Valor(Checkpoint cp,string bloco,string valor,string chaveCol,string chave){var b=cp.Blocos.FirstOrDefault(x=>x.Chave==bloco);if(b?.Erro is not null||b is null)return null;var ik=b.Colunas.ToList().IndexOf(chaveCol);var iv=b.Colunas.ToList().IndexOf(valor);if(ik<0||iv<0)return null;var l=b.Linhas.FirstOrDefault(x=>string.Equals(x[ik],chave,StringComparison.OrdinalIgnoreCase));return l is not null&&double.TryParse(l[iv],NumberStyles.Any,CultureInfo.InvariantCulture,out var v)?v:null;}
    private static string? Campo(Bloco b,IReadOnlyList<string?> l,string c){var i=b.Colunas.ToList().IndexOf(c);return i>=0?l[i]:null;}
}
