version: 2
updates:
  - package-ecosystem: nuget
    directory: /Solution
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      nuget-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
