-- Jornada PostgreSQL: catálogo de modelos e parâmetros do Linkage.
-- Fatia aditiva de leitura/scoring. Não instala runner, calibrador nem publicação.
-- O modelo e sua normalização são versionados; nenhum modelo é ativado por este script.
CREATE SCHEMA IF NOT EXISTS identidade;

CREATE TABLE IF NOT EXISTS identidade.modelo_linkage(
    modelo_id UUID PRIMARY KEY,
    versao INTEGER NOT NULL UNIQUE CHECK(versao > 0),
    status VARCHAR(20) NOT NULL CHECK(status IN('GERANDO','RASCUNHO','VALIDADO','ATIVO','INATIVO','FALHOU')),
    algoritmo_versao VARCHAR(80) NOT NULL,
    normalizacao_versao VARCHAR(80) NOT NULL,
    deduplicacao_metodo VARCHAR(120) NOT NULL,
    base_referencia VARCHAR(200) NOT NULL,
    snapshot_referencia VARCHAR(300) NULL,
    registros_lidos BIGINT NULL CHECK(registros_lidos >= 0),
    pessoas_unicas BIGINT NULL CHECK(pessoas_unicas >= 0),
    gerado_em TIMESTAMPTZ NOT NULL,
    ativado_em TIMESTAMPTZ NULL,
    snapshot_capturado_em TIMESTAMP NULL,
    amostra_metodo VARCHAR(80) NULL,
    amostra_pool_tamanho INTEGER NULL CHECK(amostra_pool_tamanho >= 0),
    amostra_m_tamanho INTEGER NULL CHECK(amostra_m_tamanho >= 0),
    amostra_u_tamanho INTEGER NULL CHECK(amostra_u_tamanho >= 0),
    falha_resumo VARCHAR(500) NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_modelo_linkage_ativo
    ON identidade.modelo_linkage(status) WHERE status='ATIVO';

CREATE TABLE IF NOT EXISTS identidade.frequencia_linkage(
    frequencia_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo_id UUID NOT NULL REFERENCES identidade.modelo_linkage(modelo_id),
    atributo VARCHAR(80) NOT NULL,
    valor_normalizado VARCHAR(500) NOT NULL,
    ocorrencias BIGINT NOT NULL CHECK(ocorrencias >= 0),
    populacao_referencia BIGINT NOT NULL CHECK(populacao_referencia > 0),
    frequencia NUMERIC(20,12) NOT NULL CHECK(frequencia >= 0 AND frequencia <= 1),
    UNIQUE(modelo_id,atributo,valor_normalizado)
);
CREATE TABLE IF NOT EXISTS identidade.estatistica_linkage(
    estatistica_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo_id UUID NOT NULL REFERENCES identidade.modelo_linkage(modelo_id),
    nome VARCHAR(100) NOT NULL,
    valor NUMERIC(30,6) NOT NULL,
    metodo VARCHAR(80) NOT NULL,
    UNIQUE(modelo_id,nome)
);
CREATE TABLE IF NOT EXISTS identidade.parametro_linkage(
    parametro_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo_id UUID NOT NULL REFERENCES identidade.modelo_linkage(modelo_id),
    nome VARCHAR(100) NOT NULL,
    valor NUMERIC(30,12) NOT NULL,
    UNIQUE(modelo_id,nome)
);

-- Uma versão validada ou publicada não pode ter suas evidências alteradas.
-- A trava do cabeçalho serializa a edição com uma futura transição de status.
CREATE OR REPLACE FUNCTION identidade.fn_linkage_evidencia_editavel()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_status VARCHAR(20); v_modelo UUID;
BEGIN
    IF TG_OP='DELETE' THEN
        v_modelo := OLD.modelo_id;
    ELSE
        v_modelo := NEW.modelo_id;
        IF TG_OP='UPDATE' AND NEW.modelo_id <> OLD.modelo_id THEN
            RAISE EXCEPTION 'Não é permitido transferir evidência entre modelos.';
        END IF;
    END IF;
    SELECT status INTO v_status FROM identidade.modelo_linkage
     WHERE modelo_id=v_modelo FOR UPDATE;
    IF v_status IS NULL OR v_status NOT IN('GERANDO','RASCUNHO') THEN
        RAISE EXCEPTION 'Evidências de modelo validado/publicado são imutáveis.';
    END IF;
    IF TG_OP='DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END $$;
DO $$
DECLARE v_table TEXT;
BEGIN
    FOREACH v_table IN ARRAY ARRAY['parametro_linkage','frequencia_linkage','estatistica_linkage'] LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS tr_pg_linkage_evidencia_editavel ON identidade.%I',v_table);
        EXECUTE format('CREATE TRIGGER tr_pg_linkage_evidencia_editavel BEFORE INSERT OR UPDATE OR DELETE ON identidade.%I FOR EACH ROW EXECUTE FUNCTION identidade.fn_linkage_evidencia_editavel()',v_table);
    END LOOP;
END $$;

CREATE OR REPLACE FUNCTION identidade.fn_linkage_modelo_imutavel()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP='DELETE' THEN
        IF OLD.status NOT IN('GERANDO','RASCUNHO','FALHOU') THEN
            RAISE EXCEPTION 'Modelo validado/publicado não pode ser excluído.';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.status IN('VALIDADO','ATIVO','INATIVO') AND
       (NEW.modelo_id,NEW.versao,NEW.algoritmo_versao,NEW.normalizacao_versao,
        NEW.deduplicacao_metodo,NEW.base_referencia,NEW.snapshot_referencia,
        NEW.registros_lidos,NEW.pessoas_unicas,NEW.gerado_em,NEW.snapshot_capturado_em,
        NEW.amostra_metodo,NEW.amostra_pool_tamanho,NEW.amostra_m_tamanho,NEW.amostra_u_tamanho)
       IS DISTINCT FROM
       (OLD.modelo_id,OLD.versao,OLD.algoritmo_versao,OLD.normalizacao_versao,
        OLD.deduplicacao_metodo,OLD.base_referencia,OLD.snapshot_referencia,
        OLD.registros_lidos,OLD.pessoas_unicas,OLD.gerado_em,OLD.snapshot_capturado_em,
        OLD.amostra_metodo,OLD.amostra_pool_tamanho,OLD.amostra_m_tamanho,OLD.amostra_u_tamanho) THEN
        RAISE EXCEPTION 'Metadados de modelo validado/publicado são imutáveis.';
    END IF;
    IF OLD.status IN('VALIDADO','ATIVO','INATIVO') AND NEW.status NOT IN('VALIDADO','ATIVO','INATIVO') THEN
        RAISE EXCEPTION 'Modelo validado não pode retornar ao estado de edição.';
    END IF;
    RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS tr_pg_linkage_modelo_imutavel ON identidade.modelo_linkage;
CREATE TRIGGER tr_pg_linkage_modelo_imutavel
BEFORE UPDATE OR DELETE ON identidade.modelo_linkage
FOR EACH ROW EXECUTE FUNCTION identidade.fn_linkage_modelo_imutavel();

-- O blocking V1/V2 deve usar índice de data e nunca varrer a Gold inteira por observação.
-- A segunda coluna auxilia a ordenação estável dos candidatos sem alterar a política de score.
CREATE INDEX IF NOT EXISTS ix_pg_gold_pessoa_nascimento_linkage
    ON gold.pessoa(data_nascimento,pessoa_uuid);

-- Projeção operacional derivada para blocking dinâmico. Não é nova verdade cadastral:
-- pode ser reconstruída integralmente a partir da Gold/histórico e da versão de normalização.
-- Nomes são aliases versionáveis; nascimento é dado estável e mudança representa correção excepcional.
CREATE TABLE IF NOT EXISTS identidade.blocking_chave(
    pessoa_uuid UUID NOT NULL REFERENCES identidade.pessoa(pessoa_uuid),
    normalizacao_versao VARCHAR(80) NOT NULL,
    atributo VARCHAR(80) NOT NULL,
    valor_normalizado VARCHAR(500) NOT NULL,
    semantica_temporal VARCHAR(30) NOT NULL CHECK(semantica_temporal IN('STABLE_IDENTITY_DATUM','VERSIONED_ALIAS')),
    vigencia_inicio TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    vigencia_fim TIMESTAMPTZ NULL,
    gerado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_pg_blocking_chave PRIMARY KEY(pessoa_uuid,normalizacao_versao,atributo,valor_normalizado,vigencia_inicio),
    CONSTRAINT ck_pg_blocking_chave_normalizacao CHECK(BTRIM(normalizacao_versao)<>''),
    CONSTRAINT ck_pg_blocking_chave_atributo CHECK(BTRIM(atributo)<>''),
    CONSTRAINT ck_pg_blocking_chave_valor CHECK(BTRIM(valor_normalizado)<>''),
    CONSTRAINT ck_pg_blocking_chave_vigencia CHECK(vigencia_fim IS NULL OR vigencia_fim>=vigencia_inicio)
);
CREATE INDEX IF NOT EXISTS ix_pg_blocking_chave_lookup
    ON identidade.blocking_chave(normalizacao_versao,atributo,valor_normalizado,vigencia_fim,pessoa_uuid);
