-- Jornada PostgreSQL - núcleo de materialização transacional do Processor.
--
-- Esta fatia porta as estruturas centrais de Silver, identidade determinística e fatos Gold/Serving
-- necessárias para a próxima implementação de PersistValidatedAsync em PostgreSQL.
-- Não declara ainda paridade integral com database/Jornada_Fase1.sql: atributos transversais,
-- geografia territorial e runtime probabilístico de linkage permanecem em fatias posteriores.

CREATE SCHEMA IF NOT EXISTS qualidade;

-- -----------------------------------------------------------------------------
-- Silver - Pessoa de origem e observações versionadas
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS silver.pessoa_origem(
    pessoa_origem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem_id BIGINT NOT NULL REFERENCES ref.sistema_origem(sistema_origem_id),
    codigo_pessoa_origem VARCHAR(255) NOT NULL,
    ultima_recepcao_em TIMESTAMPTZ NULL,
    ultima_referencia_recebida TIMESTAMPTZ NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_pg_pessoa_origem UNIQUE(sistema_origem_id,codigo_pessoa_origem),
    CONSTRAINT uq_pg_pessoa_origem_id_codigo UNIQUE(pessoa_origem_id,codigo_pessoa_origem)
);

CREATE TABLE IF NOT EXISTS silver.pessoa_observacao(
    pessoa_observacao_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_origem_id BIGINT NOT NULL,
    lote_id UUID NOT NULL REFERENCES ingestao.lote(lote_id),
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    codigo_pessoa_origem VARCHAR(255) NOT NULL,
    versao_interna INTEGER NOT NULL,
    conteudo_hash CHAR(64) NOT NULL,
    cpf CHAR(11) NULL,
    cpf_ausente_motivo VARCHAR(30) NULL,
    nome_completo VARCHAR(500) NOT NULL,
    nome_cmp VARCHAR(500) NOT NULL,
    data_nascimento DATE NOT NULL,
    nome_mae VARCHAR(500) NOT NULL,
    nome_mae_cmp VARCHAR(500) NOT NULL,
    source_as_of TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_pg_pessoa_observacao_origem
        FOREIGN KEY(pessoa_origem_id,codigo_pessoa_origem)
        REFERENCES silver.pessoa_origem(pessoa_origem_id,codigo_pessoa_origem),
    CONSTRAINT uq_pg_pessoa_observacao_versao UNIQUE(pessoa_origem_id,versao_interna),
    CONSTRAINT ck_pg_pessoa_observacao_versao CHECK(versao_interna>=1),
    CONSTRAINT ck_pg_pessoa_observacao_hash CHECK(conteudo_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_pg_pessoa_cpf_motivo CHECK(
        (cpf IS NULL AND cpf_ausente_motivo IN('SEM_CPF','EM_REGULARIZACAO','NAO_INFORMADO_ORIGEM'))
        OR (cpf IS NOT NULL AND cpf_ausente_motivo IS NULL))
);

CREATE INDEX IF NOT EXISTS ix_pg_pessoa_observacao_origem_corrente
    ON silver.pessoa_observacao(pessoa_origem_id,versao_interna DESC);
CREATE INDEX IF NOT EXISTS ix_pg_pessoa_observacao_nascimento
    ON silver.pessoa_observacao(data_nascimento,pessoa_observacao_id);

-- Conferência documental do núcleo. Não armazena imagem/documento.
CREATE TABLE IF NOT EXISTS silver.pessoa_campo_verificacao_observacao(
    pessoa_campo_verificacao_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_observacao_id BIGINT NOT NULL REFERENCES silver.pessoa_observacao(pessoa_observacao_id),
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    campo_codigo VARCHAR(40) NOT NULL,
    evidencia_tipo VARCHAR(80) NOT NULL,
    referencia_evidencia VARCHAR(255) NULL,
    verificado_em TIMESTAMPTZ NOT NULL,
    source_transaction_id VARCHAR(255) NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pg_pessoa_campo_verificacao_codigo
        CHECK(campo_codigo IN('CPF','NOME_COMPLETO','DATA_NASCIMENTO','NOME_MAE')),
    CONSTRAINT uq_pg_pessoa_campo_verificacao UNIQUE(pessoa_observacao_id,campo_codigo)
);

-- -----------------------------------------------------------------------------
-- Silver - fatos versionados por chave estável do sistema de origem
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS silver.registro_origem(
    registro_origem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem_id BIGINT NOT NULL REFERENCES ref.sistema_origem(sistema_origem_id),
    codigo_registro_origem VARCHAR(255) NOT NULL,
    natureza VARCHAR(30) NOT NULL,
    tipo_registro_id BIGINT NOT NULL REFERENCES ref.tipo_registro(tipo_registro_id),
    ultima_recepcao_em TIMESTAMPTZ NULL,
    ultima_referencia_recebida TIMESTAMPTZ NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_pg_registro_origem UNIQUE(sistema_origem_id,codigo_registro_origem),
    CONSTRAINT uq_pg_registro_origem_id_codigo UNIQUE(registro_origem_id,codigo_registro_origem),
    CONSTRAINT ck_pg_registro_origem_natureza CHECK(natureza IN('BENEFICIO','SERVICO'))
);

CREATE TABLE IF NOT EXISTS silver.registro_observacao(
    registro_observacao_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_origem_id BIGINT NOT NULL,
    codigo_registro_origem VARCHAR(255) NOT NULL,
    versao_interna INTEGER NOT NULL,
    operacao VARCHAR(20) NOT NULL,
    conteudo_hash CHAR(64) NOT NULL,
    lote_id UUID NOT NULL REFERENCES ingestao.lote(lote_id),
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    natureza VARCHAR(30) NOT NULL,
    tipo_registro_id BIGINT NOT NULL REFERENCES ref.tipo_registro(tipo_registro_id),
    tipo_registro_versao_id BIGINT NOT NULL REFERENCES ref.tipo_registro_versao(tipo_registro_versao_id),
    pessoa_observacao_id BIGINT NOT NULL REFERENCES silver.pessoa_observacao(pessoa_observacao_id),
    data_inicio_concessao DATE NULL,
    data_fim_concessao DATE NULL,
    data_evento_concessao DATE NULL,
    data_hora_servico TIMESTAMPTZ NULL,
    unidade_servico VARCHAR(200) NULL,
    situacao VARCHAR(80) NULL,
    situacao_vigencia VARCHAR(20) NULL,
    situacao_vigencia_desde DATE NULL,
    motivo_encerramento VARCHAR(30) NULL,
    valor_concedido NUMERIC(18,2) NULL,
    quantidade NUMERIC(18,4) NULL,
    unidade VARCHAR(50) NULL,
    sujeito_declarado_hash CHAR(64) NULL,
    source_as_of TIMESTAMPTZ NOT NULL,
    registrado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pg_registro_observacao_origem
        FOREIGN KEY(registro_origem_id,codigo_registro_origem)
        REFERENCES silver.registro_origem(registro_origem_id,codigo_registro_origem),
    CONSTRAINT uq_pg_registro_observacao_versao UNIQUE(registro_origem_id,versao_interna),
    CONSTRAINT ck_pg_registro_observacao_operacao CHECK(operacao IN('INCLUSAO','ALTERACAO','RETIFICACAO','EXCLUSAO')),
    CONSTRAINT ck_pg_registro_observacao_versao CHECK(versao_interna>=1),
    CONSTRAINT ck_pg_registro_observacao_hash CHECK(conteudo_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_pg_registro_sujeito_hash CHECK(sujeito_declarado_hash IS NULL OR sujeito_declarado_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_pg_registro_observacao_natureza CHECK(
        (natureza='BENEFICIO' AND data_hora_servico IS NULL AND unidade_servico IS NULL)
        OR
        (natureza='SERVICO' AND valor_concedido IS NULL AND quantidade IS NULL AND unidade IS NULL
            AND data_inicio_concessao IS NULL AND data_fim_concessao IS NULL AND data_evento_concessao IS NULL
            AND situacao_vigencia IS NULL AND situacao_vigencia_desde IS NULL AND motivo_encerramento IS NULL))
);

CREATE INDEX IF NOT EXISTS ix_pg_registro_observacao_origem_corrente
    ON silver.registro_observacao(registro_origem_id,versao_interna DESC);

-- -----------------------------------------------------------------------------
-- Identidade - núcleo determinístico e vínculo da observação
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identidade.pessoa(
    pessoa_uuid UUID PRIMARY KEY,
    status VARCHAR(30) NOT NULL,
    pessoa_uuid_sucessor UUID NULL REFERENCES identidade.pessoa(pessoa_uuid),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pg_identidade_pessoa_status CHECK(status IN('ATIVO','FUNDIDO','SEPARADO','INATIVO')),
    CONSTRAINT ck_pg_identidade_pessoa_sucessor CHECK(pessoa_uuid_sucessor IS NULL OR pessoa_uuid_sucessor<>pessoa_uuid)
);

CREATE INDEX IF NOT EXISTS ix_pg_identidade_pessoa_sucessor
    ON identidade.pessoa(pessoa_uuid_sucessor)
    WHERE pessoa_uuid_sucessor IS NOT NULL;

CREATE TABLE IF NOT EXISTS identidade.identity_map(
    identity_map_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_uuid UUID NOT NULL REFERENCES identidade.pessoa(pessoa_uuid),
    tipo VARCHAR(30) NOT NULL,
    identificador VARCHAR(255) NOT NULL,
    vigencia_inicio TIMESTAMPTZ NOT NULL,
    vigencia_fim TIMESTAMPTZ NULL,
    gestor_origem_id BIGINT NULL REFERENCES ref.gestor(gestor_id),
    source_record_id VARCHAR(255) NULL,
    metodo_resolucao VARCHAR(40) NOT NULL,
    score NUMERIC(9,8) NULL,
    modelo_id UUID NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
    estado_motivo VARCHAR(120) NULL,
    estado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pg_identity_map_tipo CHECK(tipo IN('CPF','NIS','CNS','LEGADO')),
    CONSTRAINT ck_pg_identity_map_vig CHECK(vigencia_fim IS NULL OR vigencia_fim>=vigencia_inicio),
    CONSTRAINT ck_pg_identity_map_estado CHECK(estado IN('ATIVO','EM_CONFLITO','ENCERRADO')),
    CONSTRAINT ck_pg_identity_map_estado_vig CHECK(
        (vigencia_fim IS NULL AND estado IN('ATIVO','EM_CONFLITO'))
        OR (vigencia_fim IS NOT NULL AND estado='ENCERRADO')),
    CONSTRAINT ck_pg_identity_map_metodo CHECK(metodo_resolucao IN('CPF_DETERMINISTICO','LINKAGE_PROBABILISTICO','CORRECAO_GOVERNADA')),
    CONSTRAINT ck_pg_identity_map_modelo CHECK(
        (metodo_resolucao IN('CPF_DETERMINISTICO','CORRECAO_GOVERNADA') AND score IS NULL AND modelo_id IS NULL)
        OR (metodo_resolucao='LINKAGE_PROBABILISTICO' AND modelo_id IS NOT NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_identity_map_cpf_corrente
    ON identidade.identity_map(tipo,identificador)
    WHERE tipo='CPF' AND vigencia_fim IS NULL;

CREATE TABLE IF NOT EXISTS identidade.vinculo_fonte(
    vinculo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_observacao_id BIGINT NOT NULL REFERENCES silver.pessoa_observacao(pessoa_observacao_id),
    pessoa_uuid UUID NULL REFERENCES identidade.pessoa(pessoa_uuid),
    metodo_resolucao VARCHAR(40) NOT NULL,
    score NUMERIC(9,8) NULL,
    status VARCHAR(30) NOT NULL,
    modelo_id UUID NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    linkage_run_id UUID NULL,
    resolvido_em TIMESTAMPTZ NULL,
    motivo VARCHAR(120) NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pg_vinculo_status CHECK(status IN('RESOLVIDO','NAO_RESOLVIDO','CONFLITO')),
    CONSTRAINT ck_pg_vinculo_status_uuid CHECK(
        (status='RESOLVIDO' AND pessoa_uuid IS NOT NULL)
        OR (status IN('NAO_RESOLVIDO','CONFLITO') AND pessoa_uuid IS NULL)),
    CONSTRAINT ck_pg_vinculo_metodo CHECK(metodo_resolucao IN(
        'CPF_DETERMINISTICO','PENDENTE_PROBABILISTICO','LINKAGE_PROBABILISTICO','CORRECAO_GOVERNADA','CONFLITO_GOVERNADO')),
    CONSTRAINT ck_pg_vinculo_modelo CHECK(
        (metodo_resolucao='CPF_DETERMINISTICO' AND score IS NULL AND modelo_id IS NULL)
        OR (metodo_resolucao='PENDENTE_PROBABILISTICO' AND score IS NULL AND modelo_id IS NULL AND pessoa_uuid IS NULL)
        OR (metodo_resolucao='LINKAGE_PROBABILISTICO' AND score IS NOT NULL AND modelo_id IS NOT NULL)
        OR (metodo_resolucao='CORRECAO_GOVERNADA' AND score IS NULL AND modelo_id IS NULL AND pessoa_uuid IS NOT NULL)
        OR (metodo_resolucao='CONFLITO_GOVERNADO' AND score IS NULL AND modelo_id IS NULL AND pessoa_uuid IS NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_vinculo_fonte_ativo
    ON identidade.vinculo_fonte(pessoa_observacao_id)
    WHERE ativo;

-- Visão corrente mínima: suficiente para a futura persistência determinística do Processor.
-- A sobreposição de linkage_run publicado será portada junto com o runtime probabilístico.
CREATE OR REPLACE VIEW identidade.v_vinculo_corrente AS
SELECT vinculo_id,pessoa_observacao_id,pessoa_uuid,metodo_resolucao,score,status,motivo,modelo_id,linkage_run_id,resolvido_em
FROM identidade.vinculo_fonte
WHERE ativo;

-- -----------------------------------------------------------------------------
-- Qualidade factual mínima
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS qualidade.qc_registro_resultado(
    qc_resultado_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_observacao_id BIGINT NOT NULL REFERENCES silver.registro_observacao(registro_observacao_id),
    resultado VARCHAR(30) NOT NULL,
    regra_codigo VARCHAR(80) NULL,
    motivo VARCHAR(500) NULL,
    executado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pg_qc_registro_resultado CHECK(resultado IN('VALIDO','DIVERGENTE','NAO_VERIFICAVEL'))
);

-- -----------------------------------------------------------------------------
-- Gold - Pessoa canônica
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gold.pessoa(
    pessoa_uuid UUID PRIMARY KEY REFERENCES identidade.pessoa(pessoa_uuid),
    cpf CHAR(11) NULL,
    status_cpf VARCHAR(30) NOT NULL,
    nome_completo VARCHAR(500) NOT NULL,
    data_nascimento DATE NOT NULL,
    nome_mae VARCHAR(500) NOT NULL,
    fontes_distintas INTEGER NOT NULL,
    estado_concordancia VARCHAR(40) NOT NULL,
    atualizado_em TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_pg_gold_pessoa_status_cpf CHECK(
        (cpf IS NOT NULL AND status_cpf='PRESENTE')
        OR (cpf IS NULL AND status_cpf IN('SEM_CPF','EM_REGULARIZACAO'))),
    CONSTRAINT ck_pg_gold_pessoa_fontes CHECK(fontes_distintas>=0),
    CONSTRAINT ck_pg_gold_pessoa_concordancia CHECK(estado_concordancia IN(
        'BASELINE_FONTE_UNICA','BASELINE_FALLBACK','CORROBORADO','DIVERGENTE','CONFLITO_EVIDENCIA'))
);

CREATE INDEX IF NOT EXISTS ix_pg_gold_pessoa_linkage_nascimento
    ON gold.pessoa(data_nascimento,pessoa_uuid);

-- -----------------------------------------------------------------------------
-- Gold/Serving - fato independente da resolução de identidade
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gold.beneficio_concedido(
    beneficio_concedido_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_observacao_id BIGINT NOT NULL UNIQUE REFERENCES silver.registro_observacao(registro_observacao_id),
    registro_origem_id BIGINT NOT NULL REFERENCES silver.registro_origem(registro_origem_id),
    codigo_registro_origem VARCHAR(255) NOT NULL,
    versao_interna INTEGER NOT NULL,
    operacao VARCHAR(20) NOT NULL,
    status_analitico VARCHAR(20) NOT NULL,
    pessoa_origem_id BIGINT NOT NULL REFERENCES silver.pessoa_origem(pessoa_origem_id),
    sistema_origem_id BIGINT NOT NULL REFERENCES ref.sistema_origem(sistema_origem_id),
    codigo_pessoa_origem VARCHAR(255) NOT NULL,
    cpf_declarado CHAR(11) NULL,
    cpf_ausente_motivo VARCHAR(30) NULL,
    pessoa_uuid UUID NULL REFERENCES identidade.pessoa(pessoa_uuid),
    estado_atribuicao_identidade VARCHAR(30) NOT NULL,
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    tipo_registro_id BIGINT NOT NULL REFERENCES ref.tipo_registro(tipo_registro_id),
    tipo_registro_versao_id BIGINT NOT NULL REFERENCES ref.tipo_registro_versao(tipo_registro_versao_id),
    entrega_id UUID NOT NULL REFERENCES ingestao.entrega(entrega_id),
    data_inicio_concessao DATE NULL,
    data_fim_concessao DATE NULL,
    data_evento_concessao DATE NULL,
    situacao_vigencia VARCHAR(20) NOT NULL,
    situacao_vigencia_desde DATE NULL,
    motivo_encerramento VARCHAR(30) NULL,
    referencia_territorial_observacao_id BIGINT NULL,
    natureza_referencia_territorial VARCHAR(50) NULL,
    subprefeitura_referencia_id BIGINT NULL,
    distrito_referencia_id BIGINT NULL,
    valor_concedido NUMERIC(18,2) NULL,
    quantidade NUMERIC(18,4) NULL,
    unidade VARCHAR(50) NULL,
    source_as_of TIMESTAMPTZ NOT NULL,
    qc_resultado VARCHAR(30) NULL,
    qc_especifico_implementado BOOLEAN NOT NULL,
    vigencia_versao_inicio TIMESTAMPTZ NOT NULL,
    vigencia_versao_fim TIMESTAMPTZ NULL,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_pg_beneficio_origem_versao UNIQUE(registro_origem_id,versao_interna),
    CONSTRAINT ck_pg_beneficio_operacao CHECK(operacao IN('INCLUSAO','ALTERACAO','RETIFICACAO')),
    CONSTRAINT ck_pg_beneficio_status CHECK(status_analitico IN('VIGENTE','HISTORICO','RETIFICADO','EXCLUIDO')),
    CONSTRAINT ck_pg_beneficio_vigencia CHECK(vigencia_versao_fim IS NULL OR vigencia_versao_fim>=vigencia_versao_inicio),
    CONSTRAINT ck_pg_beneficio_identidade CHECK(
        estado_atribuicao_identidade IN('ATRIBUIDA','PENDENTE_IDENTIDADE','CONFLITO_IDENTIDADE')
        AND ((estado_atribuicao_identidade='ATRIBUIDA' AND pessoa_uuid IS NOT NULL)
          OR (estado_atribuicao_identidade IN('PENDENTE_IDENTIDADE','CONFLITO_IDENTIDADE') AND pessoa_uuid IS NULL))),
    CONSTRAINT ck_pg_beneficio_cpf_motivo CHECK(
        (cpf_declarado IS NULL AND cpf_ausente_motivo IN('SEM_CPF','EM_REGULARIZACAO','NAO_INFORMADO_ORIGEM'))
        OR (cpf_declarado IS NOT NULL AND cpf_ausente_motivo IS NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_beneficio_corrente
    ON gold.beneficio_concedido(registro_origem_id)
    WHERE status_analitico='VIGENTE';

CREATE TABLE IF NOT EXISTS gold.servico_prestado(
    servico_prestado_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_observacao_id BIGINT NOT NULL UNIQUE REFERENCES silver.registro_observacao(registro_observacao_id),
    registro_origem_id BIGINT NOT NULL REFERENCES silver.registro_origem(registro_origem_id),
    codigo_registro_origem VARCHAR(255) NOT NULL,
    versao_interna INTEGER NOT NULL,
    operacao VARCHAR(20) NOT NULL,
    status_analitico VARCHAR(20) NOT NULL,
    pessoa_origem_id BIGINT NOT NULL REFERENCES silver.pessoa_origem(pessoa_origem_id),
    sistema_origem_id BIGINT NOT NULL REFERENCES ref.sistema_origem(sistema_origem_id),
    codigo_pessoa_origem VARCHAR(255) NOT NULL,
    cpf_declarado CHAR(11) NULL,
    cpf_ausente_motivo VARCHAR(30) NULL,
    pessoa_uuid UUID NULL REFERENCES identidade.pessoa(pessoa_uuid),
    estado_atribuicao_identidade VARCHAR(30) NOT NULL,
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    tipo_registro_id BIGINT NOT NULL REFERENCES ref.tipo_registro(tipo_registro_id),
    tipo_registro_versao_id BIGINT NOT NULL REFERENCES ref.tipo_registro_versao(tipo_registro_versao_id),
    entrega_id UUID NOT NULL REFERENCES ingestao.entrega(entrega_id),
    data_hora_servico TIMESTAMPTZ NULL,
    unidade_servico VARCHAR(200) NULL,
    situacao VARCHAR(80) NULL,
    referencia_territorial_observacao_id BIGINT NULL,
    natureza_referencia_territorial VARCHAR(50) NULL,
    subprefeitura_referencia_id BIGINT NULL,
    distrito_referencia_id BIGINT NULL,
    source_as_of TIMESTAMPTZ NOT NULL,
    vigencia_versao_inicio TIMESTAMPTZ NOT NULL,
    vigencia_versao_fim TIMESTAMPTZ NULL,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_pg_servico_origem_versao UNIQUE(registro_origem_id,versao_interna),
    CONSTRAINT ck_pg_servico_operacao CHECK(operacao IN('INCLUSAO','ALTERACAO','RETIFICACAO')),
    CONSTRAINT ck_pg_servico_status CHECK(status_analitico IN('VIGENTE','HISTORICO','RETIFICADO','EXCLUIDO')),
    CONSTRAINT ck_pg_servico_vigencia CHECK(vigencia_versao_fim IS NULL OR vigencia_versao_fim>=vigencia_versao_inicio),
    CONSTRAINT ck_pg_servico_identidade CHECK(
        estado_atribuicao_identidade IN('ATRIBUIDA','PENDENTE_IDENTIDADE','CONFLITO_IDENTIDADE')
        AND ((estado_atribuicao_identidade='ATRIBUIDA' AND pessoa_uuid IS NOT NULL)
          OR (estado_atribuicao_identidade IN('PENDENTE_IDENTIDADE','CONFLITO_IDENTIDADE') AND pessoa_uuid IS NULL))),
    CONSTRAINT ck_pg_servico_cpf_motivo CHECK(
        (cpf_declarado IS NULL AND cpf_ausente_motivo IN('SEM_CPF','EM_REGULARIZACAO','NAO_INFORMADO_ORIGEM'))
        OR (cpf_declarado IS NOT NULL AND cpf_ausente_motivo IS NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_servico_corrente
    ON gold.servico_prestado(registro_origem_id)
    WHERE status_analitico='VIGENTE';

CREATE TABLE IF NOT EXISTS serving.registro_integrado(
    registro_observacao_id BIGINT PRIMARY KEY REFERENCES silver.registro_observacao(registro_observacao_id),
    registro_origem_id BIGINT NOT NULL REFERENCES silver.registro_origem(registro_origem_id),
    codigo_registro_origem VARCHAR(255) NOT NULL,
    versao_interna INTEGER NOT NULL,
    operacao VARCHAR(20) NOT NULL,
    status_analitico VARCHAR(20) NOT NULL,
    pessoa_origem_id BIGINT NOT NULL REFERENCES silver.pessoa_origem(pessoa_origem_id),
    sistema_origem_id BIGINT NOT NULL REFERENCES ref.sistema_origem(sistema_origem_id),
    codigo_pessoa_origem VARCHAR(255) NOT NULL,
    cpf_declarado CHAR(11) NULL,
    cpf_ausente_motivo VARCHAR(30) NULL,
    pessoa_uuid UUID NULL REFERENCES identidade.pessoa(pessoa_uuid),
    estado_atribuicao_identidade VARCHAR(30) NOT NULL,
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    natureza VARCHAR(30) NOT NULL,
    tipo_registro_id BIGINT NOT NULL REFERENCES ref.tipo_registro(tipo_registro_id),
    tipo_registro_versao_id BIGINT NOT NULL REFERENCES ref.tipo_registro_versao(tipo_registro_versao_id),
    entrega_id UUID NOT NULL REFERENCES ingestao.entrega(entrega_id),
    entrega_completa BOOLEAN NOT NULL DEFAULT FALSE,
    data_inicio_concessao DATE NULL,
    data_fim_concessao DATE NULL,
    data_evento_concessao DATE NULL,
    situacao_vigencia VARCHAR(20) NULL,
    situacao_vigencia_desde DATE NULL,
    motivo_encerramento VARCHAR(30) NULL,
    data_hora_servico TIMESTAMPTZ NULL,
    unidade_servico VARCHAR(200) NULL,
    situacao VARCHAR(80) NULL,
    referencia_territorial_observacao_id BIGINT NULL,
    natureza_referencia_territorial VARCHAR(50) NULL,
    subprefeitura_referencia_id BIGINT NULL,
    distrito_referencia_id BIGINT NULL,
    valor_concedido NUMERIC(18,2) NULL,
    quantidade NUMERIC(18,4) NULL,
    unidade VARCHAR(50) NULL,
    source_as_of TIMESTAMPTZ NOT NULL,
    qc_resultado VARCHAR(30) NULL,
    qc_especifico_implementado BOOLEAN NULL,
    vigencia_versao_inicio TIMESTAMPTZ NOT NULL,
    vigencia_versao_fim TIMESTAMPTZ NULL,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_pg_serving_origem_versao UNIQUE(registro_origem_id,versao_interna),
    CONSTRAINT ck_pg_serving_operacao CHECK(operacao IN('INCLUSAO','ALTERACAO','RETIFICACAO')),
    CONSTRAINT ck_pg_serving_status CHECK(status_analitico IN('VIGENTE','HISTORICO','RETIFICADO','EXCLUIDO')),
    CONSTRAINT ck_pg_serving_vigencia CHECK(vigencia_versao_fim IS NULL OR vigencia_versao_fim>=vigencia_versao_inicio),
    CONSTRAINT ck_pg_serving_identidade CHECK(
        estado_atribuicao_identidade IN('ATRIBUIDA','PENDENTE_IDENTIDADE','CONFLITO_IDENTIDADE')
        AND ((estado_atribuicao_identidade='ATRIBUIDA' AND pessoa_uuid IS NOT NULL)
          OR (estado_atribuicao_identidade IN('PENDENTE_IDENTIDADE','CONFLITO_IDENTIDADE') AND pessoa_uuid IS NULL))),
    CONSTRAINT ck_pg_serving_natureza CHECK(
        (natureza='BENEFICIO' AND data_hora_servico IS NULL AND unidade_servico IS NULL)
        OR
        (natureza='SERVICO' AND valor_concedido IS NULL AND quantidade IS NULL AND unidade IS NULL
            AND data_inicio_concessao IS NULL AND data_fim_concessao IS NULL AND data_evento_concessao IS NULL
            AND situacao_vigencia IS NULL AND situacao_vigencia_desde IS NULL AND motivo_encerramento IS NULL)),
    CONSTRAINT ck_pg_serving_cpf_motivo CHECK(
        (cpf_declarado IS NULL AND cpf_ausente_motivo IN('SEM_CPF','EM_REGULARIZACAO','NAO_INFORMADO_ORIGEM'))
        OR (cpf_declarado IS NOT NULL AND cpf_ausente_motivo IS NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_serving_corrente
    ON serving.registro_integrado(registro_origem_id)
    WHERE status_analitico='VIGENTE';

-- -----------------------------------------------------------------------------
-- Resultado detalhado do Processor: evolui a tabela operacional existente sem
-- quebrar a Jornada.Resultado.Api já entregue.
-- -----------------------------------------------------------------------------
ALTER TABLE ingestao.item_processado
    ADD COLUMN IF NOT EXISTS pessoa_origem_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS registro_origem_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS codigo_origem VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS versao_interna INTEGER NULL,
    ADD COLUMN IF NOT EXISTS conteudo_hash CHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS data_referencia TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS processado_em TIMESTAMPTZ NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_pg_item_processado_pessoa_origem') THEN
        ALTER TABLE ingestao.item_processado
            ADD CONSTRAINT fk_pg_item_processado_pessoa_origem
            FOREIGN KEY(pessoa_origem_id) REFERENCES silver.pessoa_origem(pessoa_origem_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_pg_item_processado_registro_origem') THEN
        ALTER TABLE ingestao.item_processado
            ADD CONSTRAINT fk_pg_item_processado_registro_origem
            FOREIGN KEY(registro_origem_id) REFERENCES silver.registro_origem(registro_origem_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='ck_pg_item_processado_origem') THEN
        ALTER TABLE ingestao.item_processado
            ADD CONSTRAINT ck_pg_item_processado_origem CHECK(
                pessoa_origem_id IS NULL OR registro_origem_id IS NULL);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='ck_pg_item_processado_hash') THEN
        ALTER TABLE ingestao.item_processado
            ADD CONSTRAINT ck_pg_item_processado_hash CHECK(
                conteudo_hash IS NULL OR conteudo_hash ~ '^[0-9a-f]{64}$');
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS ix_pg_item_processado_origens
    ON ingestao.item_processado(pessoa_origem_id,registro_origem_id)
    WHERE pessoa_origem_id IS NOT NULL OR registro_origem_id IS NOT NULL;
