-- Jornada PostgreSQL - primeira fatia operacional portável.
-- Escopo atual: estruturas necessárias ao adapter, coordenação e Jornada.Resultado.Api.
-- Não representa ainda paridade integral com database/Jornada_Fase1.sql.

CREATE SCHEMA IF NOT EXISTS ref;
CREATE SCHEMA IF NOT EXISTS ingestao;
CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS controle;
CREATE SCHEMA IF NOT EXISTS identidade;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;
CREATE SCHEMA IF NOT EXISTS serving;
CREATE SCHEMA IF NOT EXISTS auditoria;

CREATE TABLE IF NOT EXISTS ref.gestor(
    gestor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    nome VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS ref.sistema_origem(
    sistema_origem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    codigo VARCHAR(80) NOT NULL,
    nome VARCHAR(200) NOT NULL,
    UNIQUE(gestor_id,codigo)
);

CREATE TABLE IF NOT EXISTS ref.gestor_pessoa_versao(
    gestor_pessoa_versao_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    versao INTEGER NOT NULL,
    UNIQUE(gestor_id,versao)
);

CREATE TABLE IF NOT EXISTS ref.tipo_registro(
    tipo_registro_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo CHAR(4) NOT NULL UNIQUE,
    nome VARCHAR(200) NOT NULL,
    CONSTRAINT ck_pg_tipo_codigo_llnn CHECK (codigo ~ '^[A-Z]{2}[0-9]{2}$')
);

CREATE TABLE IF NOT EXISTS ref.tipo_registro_versao(
    tipo_registro_versao_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_registro_id BIGINT NOT NULL REFERENCES ref.tipo_registro(tipo_registro_id),
    versao INTEGER NOT NULL,
    UNIQUE(tipo_registro_id,versao)
);

CREATE TABLE IF NOT EXISTS ingestao.entrega(
    entrega_id UUID PRIMARY KEY,
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    sistema_origem_id BIGINT NOT NULL REFERENCES ref.sistema_origem(sistema_origem_id),
    gestor_pessoa_versao_id BIGINT NOT NULL REFERENCES ref.gestor_pessoa_versao(gestor_pessoa_versao_id),
    natureza VARCHAR(30) NULL,
    tipo_registro_id BIGINT NULL REFERENCES ref.tipo_registro(tipo_registro_id),
    tipo_registro_versao_id BIGINT NULL REFERENCES ref.tipo_registro_versao(tipo_registro_versao_id),
    idempotency_key VARCHAR(200) NOT NULL,
    payload_sha256 CHAR(64) NOT NULL,
    bytes_recebidos BIGINT NOT NULL CHECK(bytes_recebidos >= 0),
    status VARCHAR(30) NOT NULL,
    data_referencia TIMESTAMPTZ NOT NULL,
    recebido_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultima_atualizacao TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(gestor_id,idempotency_key)
);

CREATE INDEX IF NOT EXISTS ix_pg_entrega_recebido
    ON ingestao.entrega(gestor_id,recebido_em DESC,entrega_id DESC);

CREATE TABLE IF NOT EXISTS bronze.entrega_arquivo(
    entrega_id UUID PRIMARY KEY REFERENCES ingestao.entrega(entrega_id) ON DELETE CASCADE,
    nome_arquivo VARCHAR(260) NOT NULL,
    content_type VARCHAR(100) NOT NULL DEFAULT 'application/zip',
    objeto_chave VARCHAR(500) NOT NULL,
    payload_sha256 CHAR(64) NOT NULL,
    tamanho_bytes BIGINT NOT NULL CHECK(tamanho_bytes >= 0),
    recebido_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_pg_bronze_nome_arquivo ON bronze.entrega_arquivo(nome_arquivo);

CREATE TABLE IF NOT EXISTS ingestao.lote(
    lote_id UUID PRIMARY KEY,
    entrega_id UUID NOT NULL REFERENCES ingestao.entrega(entrega_id) ON DELETE CASCADE,
    lote_seq INTEGER NOT NULL,
    lote_total INTEGER NOT NULL,
    qtd_pessoas INTEGER NOT NULL DEFAULT 0,
    qtd_registros INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    erro_codigo VARCHAR(100) NULL,
    tentativa_count INTEGER NOT NULL DEFAULT 0,
    recuperacao_count INTEGER NOT NULL DEFAULT 0,
    ultima_tentativa_em TIMESTAMPTZ NULL,
    proxima_tentativa_em TIMESTAMPTZ NULL,
    poison_em TIMESTAMPTZ NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(entrega_id,lote_seq)
);

CREATE TABLE IF NOT EXISTS ingestao.item_processado(
    item_processado_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_id UUID NOT NULL REFERENCES ingestao.lote(lote_id) ON DELETE CASCADE,
    classe_item VARCHAR(30) NOT NULL,
    resultado VARCHAR(40) NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_pg_item_processado_lote_resultado
    ON ingestao.item_processado(lote_id,classe_item,resultado);

CREATE TABLE IF NOT EXISTS ingestao.item_processado_resumo(
    entrega_id UUID NOT NULL REFERENCES ingestao.entrega(entrega_id) ON DELETE CASCADE,
    classe_item VARCHAR(30) NOT NULL,
    resultado VARCHAR(40) NOT NULL,
    quantidade BIGINT NOT NULL CHECK(quantidade >= 0),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(entrega_id,classe_item,resultado)
);
