-- Jornada PostgreSQL - persistência do Processor (Silver/Identidade/Gold/Serving).
--
-- Escopo desta fatia:
--   * observações cadastrais e factuais versionadas;
--   * identidade determinística por CPF e vínculo de observação;
--   * atributos transversais, conferência documental e referência territorial;
--   * materialização Gold/Serving de benefícios e serviços;
--   * QC factual e divergência de identidade.
--
-- Não declara paridade do subsistema analítico de Linkage (calibração/runner Fellegi-Sunter).
-- O Processor pode manter observações sem CPF como PENDENTE_IDENTIDADE até esse subsistema ser portado.

CREATE SCHEMA IF NOT EXISTS qualidade;

-- Catálogo transversal consumido pelo Processor. Novo atributo continua sendo dado de catálogo,
-- não ALTER TABLE em gold.pessoa.
CREATE TABLE IF NOT EXISTS ref.atributo_transversal(
    atributo_codigo VARCHAR(80) PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    formato_codigo VARCHAR(80) NOT NULL,
    regra_temporal_codigo VARCHAR(80) NOT NULL,
    cardinalidade VARCHAR(10) NOT NULL CHECK(cardinalidade IN ('SINGLE','MULTI')),
    chave_instancia_codigo VARCHAR(80) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO ref.atributo_transversal(
    atributo_codigo,nome,formato_codigo,regra_temporal_codigo,cardinalidade,chave_instancia_codigo,ativo)
VALUES
 ('ENDERECO_RESIDENCIAL','Endereço residencial','ENDERECO_CANONICO_V1','REFERENCIA_EVIDENCIA_OU_VERIFICADO_EM_V1','SINGLE','UNICA_V1',TRUE),
 ('ENDERECO_CASA_ABRIGO_SIGILOSA','Endereço de casa-abrigo-sigilosa','ENDERECO_CANONICO_V1','REFERENCIA_EVIDENCIA_OU_VERIFICADO_EM_V1','SINGLE','UNICA_V1',TRUE),
 ('REFERENCIA_TERRITORIAL','Referência territorial da Pessoa','REFERENCIA_TERRITORIAL_V1','REFERENCIA_EVIDENCIA_OU_VERIFICADO_EM_V1','SINGLE','UNICA_V1',TRUE),
 ('TELEFONE_CONTATO','Telefone de contato','TELEFONE_V1','REFERENCIA_EVIDENCIA_OU_VERIFICADO_EM_V1','MULTI','TELEFONE_BR_CANONICO_V2',TRUE),
 ('EMAIL_CONTATO','E-mail de contato','EMAIL_V1','REFERENCIA_EVIDENCIA_OU_VERIFICADO_EM_V1','MULTI','EMAIL_CANONICO_V2',TRUE),
 ('NOME_SOCIAL','Nome social','TEXTO_UTF8_V1','REFERENCIA_EVIDENCIA_OU_VERIFICADO_EM_V1','SINGLE','UNICA_V1',TRUE)
ON CONFLICT(atributo_codigo) DO UPDATE SET
    nome=EXCLUDED.nome,
    formato_codigo=EXCLUDED.formato_codigo,
    regra_temporal_codigo=EXCLUDED.regra_temporal_codigo,
    cardinalidade=EXCLUDED.cardinalidade,
    chave_instancia_codigo=EXCLUDED.chave_instancia_codigo,
    ativo=EXCLUDED.ativo;

CREATE TABLE IF NOT EXISTS ref.subprefeitura(
    subprefeitura_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL,
    nome VARCHAR(150) NOT NULL,
    observado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(codigo,nome)
);

CREATE TABLE IF NOT EXISTS ref.distrito(
    distrito_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subprefeitura_id BIGINT NOT NULL REFERENCES ref.subprefeitura(subprefeitura_id),
    codigo VARCHAR(30) NOT NULL,
    nome VARCHAR(150) NOT NULL,
    observado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(subprefeitura_id,codigo,nome)
);

CREATE TABLE IF NOT EXISTS silver.pessoa_origem(
    pessoa_origem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem_id BIGINT NOT NULL REFERENCES ref.sistema_origem(sistema_origem_id),
    codigo_pessoa_origem VARCHAR(255) NOT NULL,
    ultima_recepcao_em TIMESTAMPTZ NULL,
    ultima_referencia_recebida TIMESTAMPTZ NULL,
    UNIQUE(sistema_origem_id,codigo_pessoa_origem)
);

CREATE TABLE IF NOT EXISTS silver.pessoa_observacao(
    pessoa_observacao_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_origem_id BIGINT NOT NULL REFERENCES silver.pessoa_origem(pessoa_origem_id),
    lote_id UUID NOT NULL REFERENCES ingestao.lote(lote_id),
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    codigo_pessoa_origem VARCHAR(255) NOT NULL,
    versao_interna INTEGER NOT NULL CHECK(versao_interna > 0),
    conteudo_hash CHAR(64) NOT NULL CHECK(conteudo_hash ~ '^[0-9a-f]{64}$'),
    cpf CHAR(11) NULL,
    cpf_ausente_motivo VARCHAR(30) NULL,
    nome_completo VARCHAR(500) NOT NULL,
    nome_cmp VARCHAR(500) NOT NULL,
    data_nascimento DATE NOT NULL,
    nome_mae VARCHAR(500) NOT NULL,
    nome_mae_cmp VARCHAR(500) NOT NULL,
    source_as_of TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(pessoa_origem_id,versao_interna)
);
CREATE INDEX IF NOT EXISTS ix_pg_pessoa_observacao_origem_corrente
    ON silver.pessoa_observacao(pessoa_origem_id,versao_interna DESC);
CREATE INDEX IF NOT EXISTS ix_pg_pessoa_observacao_cpf
    ON silver.pessoa_observacao(cpf) WHERE cpf IS NOT NULL;

CREATE TABLE IF NOT EXISTS silver.pessoa_campo_verificacao_observacao(
    pessoa_campo_verificacao_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_observacao_id BIGINT NOT NULL REFERENCES silver.pessoa_observacao(pessoa_observacao_id) ON DELETE CASCADE,
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    campo_codigo VARCHAR(40) NOT NULL,
    evidencia_tipo VARCHAR(80) NOT NULL,
    referencia_evidencia VARCHAR(255) NULL,
    verificado_em TIMESTAMPTZ NOT NULL,
    source_transaction_id VARCHAR(255) NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(pessoa_observacao_id,campo_codigo)
);

CREATE TABLE IF NOT EXISTS silver.pessoa_atributo_observacao(
    pessoa_atributo_observacao_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_record_id VARCHAR(255) NULL,
    pessoa_observacao_id BIGINT NOT NULL REFERENCES silver.pessoa_observacao(pessoa_observacao_id) ON DELETE CASCADE,
    fonte_gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    atributo_codigo VARCHAR(80) NOT NULL REFERENCES ref.atributo_transversal(atributo_codigo),
    atributo_instancia_chave VARCHAR(512) NOT NULL,
    valor VARCHAR(2000) NOT NULL,
    status_evidencia VARCHAR(20) NOT NULL,
    evidencia_tipo VARCHAR(80) NULL,
    referencia_evidencia TIMESTAMPTZ NULL,
    verificado_em TIMESTAMPTZ NULL,
    atualizado_em_origem TIMESTAMPTZ NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pg_atributo_comprovado_verificado CHECK(status_evidencia <> 'COMPROVADO' OR verificado_em IS NOT NULL),
    UNIQUE(pessoa_observacao_id,atributo_codigo,atributo_instancia_chave)
);

CREATE TABLE IF NOT EXISTS silver.referencia_territorial_observacao(
    referencia_territorial_observacao_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_atributo_observacao_id BIGINT NOT NULL UNIQUE REFERENCES silver.pessoa_atributo_observacao(pessoa_atributo_observacao_id) ON DELETE CASCADE,
    natureza_referencia VARCHAR(50) NOT NULL CHECK(natureza_referencia IN ('DOMICILIAR','ACOLHIMENTO_INSTITUCIONAL','REFERENCIA_TERRITORIAL_DECLARADA')),
    fonte_semantica VARCHAR(30) NOT NULL CHECK(fonte_semantica IN ('REFERENCIA_TERRITORIAL','ENDERECO_RESIDENCIAL')),
    subprefeitura_id BIGINT NULL REFERENCES ref.subprefeitura(subprefeitura_id),
    distrito_id BIGINT NULL REFERENCES ref.distrito(distrito_id),
    situacao_geografia VARCHAR(40) NULL CHECK(situacao_geografia IS NULL OR situacao_geografia IN ('RESOLVIDA','FORA_MUNICIPIO','SEM_ENDERECO_APTO','NAO_RESOLVIDA_ORIGEM')),
    origem_geografia VARCHAR(30) NULL,
    referencia_malha VARCHAR(120) NULL,
    resolvido_em TIMESTAMPTZ NULL,
    CONSTRAINT ck_pg_referencia_domiciliar CHECK(fonte_semantica <> 'ENDERECO_RESIDENCIAL' OR natureza_referencia='DOMICILIAR'),
    CONSTRAINT ck_pg_referencia_geo_coerente CHECK(
        (situacao_geografia='RESOLVIDA' AND subprefeitura_id IS NOT NULL AND distrito_id IS NOT NULL AND referencia_malha IS NOT NULL AND resolvido_em IS NOT NULL)
        OR (situacao_geografia IS DISTINCT FROM 'RESOLVIDA' AND subprefeitura_id IS NULL AND distrito_id IS NULL AND origem_geografia IS NULL AND referencia_malha IS NULL AND resolvido_em IS NULL)
    )
);

CREATE OR REPLACE VIEW silver.v_pessoa_referencia_territorial AS
SELECT po.pessoa_observacao_id,
       x.referencia_territorial_observacao_id,
       x.pessoa_atributo_observacao_id,
       x.natureza_referencia,
       x.fonte_semantica,
       x.subprefeitura_id,
       x.distrito_id,
       x.situacao_geografia,
       x.origem_geografia,
       x.referencia_malha,
       x.resolvido_em
FROM silver.pessoa_observacao po
LEFT JOIN LATERAL (
    SELECT rt.referencia_territorial_observacao_id,
           pa.pessoa_atributo_observacao_id,
           rt.natureza_referencia,
           rt.fonte_semantica,
           rt.subprefeitura_id,
           rt.distrito_id,
           rt.situacao_geografia,
           rt.origem_geografia,
           rt.referencia_malha,
           rt.resolvido_em
      FROM silver.pessoa_atributo_observacao pa
      JOIN silver.referencia_territorial_observacao rt
        ON rt.pessoa_atributo_observacao_id=pa.pessoa_atributo_observacao_id
     WHERE pa.pessoa_observacao_id=po.pessoa_observacao_id
     ORDER BY CASE WHEN rt.fonte_semantica='REFERENCIA_TERRITORIAL' THEN 0 ELSE 1 END,
              CASE WHEN pa.status_evidencia='COMPROVADO' THEN 0 ELSE 1 END,
              COALESCE(pa.referencia_evidencia,pa.verificado_em,pa.atualizado_em_origem,pa.ingested_at) DESC,
              pa.pessoa_atributo_observacao_id DESC
     LIMIT 1
) x ON TRUE;

CREATE TABLE IF NOT EXISTS silver.registro_origem(
    registro_origem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem_id BIGINT NOT NULL REFERENCES ref.sistema_origem(sistema_origem_id),
    natureza VARCHAR(30) NOT NULL CHECK(natureza IN ('BENEFICIO','SERVICO')),
    tipo_registro_id BIGINT NOT NULL REFERENCES ref.tipo_registro(tipo_registro_id),
    codigo_registro_origem VARCHAR(255) NOT NULL,
    ultima_recepcao_em TIMESTAMPTZ NULL,
    ultima_referencia_recebida TIMESTAMPTZ NULL,
    UNIQUE(sistema_origem_id,natureza,tipo_registro_id,codigo_registro_origem)
);

CREATE TABLE IF NOT EXISTS silver.registro_observacao(
    registro_observacao_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_origem_id BIGINT NOT NULL REFERENCES silver.registro_origem(registro_origem_id),
    codigo_registro_origem VARCHAR(255) NOT NULL,
    versao_interna INTEGER NOT NULL CHECK(versao_interna > 0),
    operacao VARCHAR(20) NOT NULL CHECK(operacao IN ('INCLUSAO','ALTERACAO','RETIFICACAO','EXCLUSAO')),
    conteudo_hash CHAR(64) NOT NULL CHECK(conteudo_hash ~ '^[0-9a-f]{64}$'),
    lote_id UUID NOT NULL REFERENCES ingestao.lote(lote_id),
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    natureza VARCHAR(30) NOT NULL CHECK(natureza IN ('BENEFICIO','SERVICO')),
    tipo_registro_id BIGINT NOT NULL REFERENCES ref.tipo_registro(tipo_registro_id),
    tipo_registro_versao_id BIGINT NOT NULL REFERENCES ref.tipo_registro_versao(tipo_registro_versao_id),
    pessoa_observacao_id BIGINT NOT NULL REFERENCES silver.pessoa_observacao(pessoa_observacao_id),
    data_inicio_concessao DATE NULL,
    data_fim_concessao DATE NULL,
    data_evento_concessao DATE NULL,
    data_hora_servico TIMESTAMPTZ NULL,
    unidade_servico VARCHAR(200) NULL,
    situacao VARCHAR(80) NULL,
    situacao_vigencia VARCHAR(20) NULL,
    situacao_vigencia_desde DATE NULL,
    motivo_encerramento VARCHAR(30) NULL,
    valor_concedido NUMERIC(18,2) NULL,
    quantidade NUMERIC(18,4) NULL,
    unidade VARCHAR(50) NULL,
    source_as_of TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(registro_origem_id,versao_interna)
);
CREATE INDEX IF NOT EXISTS ix_pg_registro_observacao_origem_corrente
    ON silver.registro_observacao(registro_origem_id,versao_interna DESC);

CREATE TABLE IF NOT EXISTS identidade.pessoa(
    pessoa_uuid UUID PRIMARY KEY,
    status VARCHAR(30) NOT NULL CHECK(status IN ('ATIVO','EM_CONFLITO','INATIVO')),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS identidade.identity_map(
    identity_map_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_uuid UUID NOT NULL REFERENCES identidade.pessoa(pessoa_uuid),
    tipo VARCHAR(30) NOT NULL,
    identificador VARCHAR(255) NOT NULL,
    vigencia_inicio TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    vigencia_fim TIMESTAMPTZ NULL,
    gestor_origem_id BIGINT NULL REFERENCES ref.gestor(gestor_id),
    source_record_id VARCHAR(255) NULL,
    metodo_resolucao VARCHAR(40) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'ATIVO' CHECK(estado IN ('ATIVO','EM_CONFLITO','INATIVO')),
    estado_motivo VARCHAR(120) NULL,
    estado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_identity_map_corrente
    ON identidade.identity_map(tipo,identificador)
    WHERE vigencia_fim IS NULL;
CREATE INDEX IF NOT EXISTS ix_pg_identity_map_pessoa
    ON identidade.identity_map(pessoa_uuid,tipo,vigencia_inicio DESC);

CREATE TABLE IF NOT EXISTS identidade.identity_map_estado_evento(
    identity_map_estado_evento_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_map_id BIGINT NOT NULL REFERENCES identidade.identity_map(identity_map_id),
    estado_anterior VARCHAR(30) NULL,
    estado_novo VARCHAR(30) NOT NULL,
    motivo VARCHAR(120) NOT NULL,
    ocorrido_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS identidade.vinculo_fonte(
    vinculo_fonte_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_observacao_id BIGINT NOT NULL REFERENCES silver.pessoa_observacao(pessoa_observacao_id) ON DELETE CASCADE,
    pessoa_uuid UUID NULL REFERENCES identidade.pessoa(pessoa_uuid),
    metodo_resolucao VARCHAR(40) NOT NULL,
    score NUMERIC(12,9) NULL,
    status VARCHAR(30) NOT NULL CHECK(status IN ('RESOLVIDO','NAO_RESOLVIDO','CONFLITO')),
    modelo_id UUID NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    resolvido_em TIMESTAMPTZ NULL,
    motivo VARCHAR(120) NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pg_vinculo_uuid_status CHECK(
        (status='RESOLVIDO' AND pessoa_uuid IS NOT NULL)
        OR (status IN ('NAO_RESOLVIDO','CONFLITO') AND pessoa_uuid IS NULL)
    )
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_vinculo_fonte_corrente
    ON identidade.vinculo_fonte(pessoa_observacao_id)
    WHERE ativo;

CREATE OR REPLACE VIEW identidade.v_vinculo_corrente AS
SELECT vinculo_fonte_id,pessoa_observacao_id,pessoa_uuid,metodo_resolucao,score,status,modelo_id,resolvido_em,motivo
FROM identidade.vinculo_fonte
WHERE ativo;

CREATE TABLE IF NOT EXISTS gold.pessoa(
    pessoa_uuid UUID PRIMARY KEY REFERENCES identidade.pessoa(pessoa_uuid),
    cpf CHAR(11) NULL,
    status_cpf VARCHAR(30) NOT NULL,
    nome_completo VARCHAR(500) NOT NULL,
    data_nascimento DATE NOT NULL,
    nome_mae VARCHAR(500) NOT NULL,
    fontes_distintas INTEGER NOT NULL DEFAULT 1 CHECK(fontes_distintas > 0),
    estado_concordancia VARCHAR(40) NOT NULL,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_gold_pessoa_cpf
    ON gold.pessoa(cpf) WHERE cpf IS NOT NULL;

CREATE TABLE IF NOT EXISTS gold.pessoa_atributo(
    pessoa_atributo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_uuid UUID NOT NULL REFERENCES identidade.pessoa(pessoa_uuid),
    atributo_codigo VARCHAR(80) NOT NULL REFERENCES ref.atributo_transversal(atributo_codigo),
    atributo_instancia_chave VARCHAR(512) NOT NULL,
    valor VARCHAR(2000) NOT NULL,
    fonte_gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    pessoa_atributo_observacao_id BIGINT NOT NULL REFERENCES silver.pessoa_atributo_observacao(pessoa_atributo_observacao_id),
    source_record_id VARCHAR(255) NULL,
    evidencia_tipo VARCHAR(80) NULL,
    referencia_evidencia TIMESTAMPTZ NULL,
    verificado_em TIMESTAMPTZ NOT NULL,
    precedencia_em TIMESTAMPTZ NOT NULL,
    vigencia_inicio TIMESTAMPTZ NOT NULL,
    vigencia_fim TIMESTAMPTZ NULL,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_gold_atributo_corrente
    ON gold.pessoa_atributo(pessoa_uuid,atributo_codigo,atributo_instancia_chave)
    WHERE vigencia_fim IS NULL;

CREATE TABLE IF NOT EXISTS qualidade.qc_registro_resultado(
    qc_registro_resultado_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_observacao_id BIGINT NOT NULL REFERENCES silver.registro_observacao(registro_observacao_id) ON DELETE CASCADE,
    resultado VARCHAR(30) NOT NULL,
    regra_codigo VARCHAR(80) NULL,
    motivo VARCHAR(500) NULL,
    executado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS qualidade.divergencia_gestor(
    divergencia_gestor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    tipo VARCHAR(60) NOT NULL,
    motivo VARCHAR(120) NOT NULL,
    pessoa_observacao_id BIGINT NULL REFERENCES silver.pessoa_observacao(pessoa_observacao_id),
    codigo_pessoa_origem VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ABERTA',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_divergencia_identidade_aberta
    ON qualidade.divergencia_gestor(gestor_id,pessoa_observacao_id,tipo,motivo)
    WHERE status='ABERTA';

-- O estado da ocorrência factual independe da atribuição canônica da Pessoa.
-- Fato válido permanece Gold mesmo com UUID pendente/conflitante.
CREATE TABLE IF NOT EXISTS gold.beneficio_concedido(
    beneficio_concedido_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_observacao_id BIGINT NOT NULL UNIQUE REFERENCES silver.registro_observacao(registro_observacao_id),
    registro_origem_id BIGINT NOT NULL REFERENCES silver.registro_origem(registro_origem_id),
    codigo_registro_origem VARCHAR(255) NOT NULL,
    versao_interna INTEGER NOT NULL,
    operacao VARCHAR(20) NOT NULL,
    status_analitico VARCHAR(20) NOT NULL CHECK(status_analitico IN ('VIGENTE','HISTORICO','RETIFICADO','EXCLUIDO')),
    pessoa_origem_id BIGINT NOT NULL REFERENCES silver.pessoa_origem(pessoa_origem_id),
    sistema_origem_id BIGINT NOT NULL REFERENCES ref.sistema_origem(sistema_origem_id),
    codigo_pessoa_origem VARCHAR(255) NOT NULL,
    cpf_declarado CHAR(11) NULL,
    cpf_ausente_motivo VARCHAR(30) NULL,
    pessoa_uuid UUID NULL REFERENCES identidade.pessoa(pessoa_uuid),
    estado_atribuicao_identidade VARCHAR(30) NOT NULL,
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    tipo_registro_id BIGINT NOT NULL REFERENCES ref.tipo_registro(tipo_registro_id),
    tipo_registro_versao_id BIGINT NOT NULL REFERENCES ref.tipo_registro_versao(tipo_registro_versao_id),
    entrega_id UUID NOT NULL REFERENCES ingestao.entrega(entrega_id),
    data_inicio_concessao DATE NULL,
    data_fim_concessao DATE NULL,
    data_evento_concessao DATE NULL,
    situacao_vigencia VARCHAR(20) NULL,
    situacao_vigencia_desde DATE NULL,
    motivo_encerramento VARCHAR(30) NULL,
    referencia_territorial_observacao_id BIGINT NULL REFERENCES silver.referencia_territorial_observacao(referencia_territorial_observacao_id),
    natureza_referencia_territorial VARCHAR(50) NULL,
    subprefeitura_referencia_id BIGINT NULL REFERENCES ref.subprefeitura(subprefeitura_id),
    distrito_referencia_id BIGINT NULL REFERENCES ref.distrito(distrito_id),
    valor_concedido NUMERIC(18,2) NULL,
    quantidade NUMERIC(18,4) NULL,
    unidade VARCHAR(50) NULL,
    source_as_of TIMESTAMPTZ NOT NULL,
    qc_resultado VARCHAR(30) NULL,
    qc_especifico_implementado BOOLEAN NOT NULL DEFAULT FALSE,
    vigencia_versao_inicio TIMESTAMPTZ NOT NULL,
    vigencia_versao_fim TIMESTAMPTZ NULL,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pg_beneficio_identidade CHECK(
        (estado_atribuicao_identidade='ATRIBUIDA' AND pessoa_uuid IS NOT NULL)
        OR (estado_atribuicao_identidade IN ('PENDENTE_IDENTIDADE','CONFLITO_IDENTIDADE') AND pessoa_uuid IS NULL)
    ),
    UNIQUE(registro_origem_id,versao_interna)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_beneficio_vigente
    ON gold.beneficio_concedido(registro_origem_id) WHERE status_analitico='VIGENTE';

CREATE TABLE IF NOT EXISTS gold.servico_prestado(
    servico_prestado_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_observacao_id BIGINT NOT NULL UNIQUE REFERENCES silver.registro_observacao(registro_observacao_id),
    registro_origem_id BIGINT NOT NULL REFERENCES silver.registro_origem(registro_origem_id),
    codigo_registro_origem VARCHAR(255) NOT NULL,
    versao_interna INTEGER NOT NULL,
    operacao VARCHAR(20) NOT NULL,
    status_analitico VARCHAR(20) NOT NULL CHECK(status_analitico IN ('VIGENTE','HISTORICO','RETIFICADO','EXCLUIDO')),
    pessoa_origem_id BIGINT NOT NULL REFERENCES silver.pessoa_origem(pessoa_origem_id),
    sistema_origem_id BIGINT NOT NULL REFERENCES ref.sistema_origem(sistema_origem_id),
    codigo_pessoa_origem VARCHAR(255) NOT NULL,
    cpf_declarado CHAR(11) NULL,
    cpf_ausente_motivo VARCHAR(30) NULL,
    pessoa_uuid UUID NULL REFERENCES identidade.pessoa(pessoa_uuid),
    estado_atribuicao_identidade VARCHAR(30) NOT NULL,
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    tipo_registro_id BIGINT NOT NULL REFERENCES ref.tipo_registro(tipo_registro_id),
    tipo_registro_versao_id BIGINT NOT NULL REFERENCES ref.tipo_registro_versao(tipo_registro_versao_id),
    entrega_id UUID NOT NULL REFERENCES ingestao.entrega(entrega_id),
    data_hora_servico TIMESTAMPTZ NULL,
    unidade_servico VARCHAR(200) NULL,
    situacao VARCHAR(80) NULL,
    referencia_territorial_observacao_id BIGINT NULL REFERENCES silver.referencia_territorial_observacao(referencia_territorial_observacao_id),
    natureza_referencia_territorial VARCHAR(50) NULL,
    subprefeitura_referencia_id BIGINT NULL REFERENCES ref.subprefeitura(subprefeitura_id),
    distrito_referencia_id BIGINT NULL REFERENCES ref.distrito(distrito_id),
    source_as_of TIMESTAMPTZ NOT NULL,
    vigencia_versao_inicio TIMESTAMPTZ NOT NULL,
    vigencia_versao_fim TIMESTAMPTZ NULL,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pg_servico_identidade CHECK(
        (estado_atribuicao_identidade='ATRIBUIDA' AND pessoa_uuid IS NOT NULL)
        OR (estado_atribuicao_identidade IN ('PENDENTE_IDENTIDADE','CONFLITO_IDENTIDADE') AND pessoa_uuid IS NULL)
    ),
    UNIQUE(registro_origem_id,versao_interna)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_servico_vigente
    ON gold.servico_prestado(registro_origem_id) WHERE status_analitico='VIGENTE';

CREATE TABLE IF NOT EXISTS serving.registro_integrado(
    registro_integrado_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_observacao_id BIGINT NOT NULL UNIQUE REFERENCES silver.registro_observacao(registro_observacao_id),
    registro_origem_id BIGINT NOT NULL REFERENCES silver.registro_origem(registro_origem_id),
    codigo_registro_origem VARCHAR(255) NOT NULL,
    versao_interna INTEGER NOT NULL,
    operacao VARCHAR(20) NOT NULL,
    status_analitico VARCHAR(20) NOT NULL CHECK(status_analitico IN ('VIGENTE','HISTORICO','RETIFICADO','EXCLUIDO')),
    pessoa_origem_id BIGINT NOT NULL REFERENCES silver.pessoa_origem(pessoa_origem_id),
    sistema_origem_id BIGINT NOT NULL REFERENCES ref.sistema_origem(sistema_origem_id),
    codigo_pessoa_origem VARCHAR(255) NOT NULL,
    cpf_declarado CHAR(11) NULL,
    cpf_ausente_motivo VARCHAR(30) NULL,
    pessoa_uuid UUID NULL REFERENCES identidade.pessoa(pessoa_uuid),
    estado_atribuicao_identidade VARCHAR(30) NOT NULL,
    gestor_id BIGINT NOT NULL REFERENCES ref.gestor(gestor_id),
    natureza VARCHAR(30) NOT NULL CHECK(natureza IN ('BENEFICIO','SERVICO')),
    tipo_registro_id BIGINT NOT NULL REFERENCES ref.tipo_registro(tipo_registro_id),
    tipo_registro_versao_id BIGINT NOT NULL REFERENCES ref.tipo_registro_versao(tipo_registro_versao_id),
    entrega_id UUID NOT NULL REFERENCES ingestao.entrega(entrega_id),
    entrega_completa BOOLEAN NOT NULL DEFAULT FALSE,
    data_inicio_concessao DATE NULL,
    data_fim_concessao DATE NULL,
    data_evento_concessao DATE NULL,
    situacao_vigencia VARCHAR(20) NULL,
    situacao_vigencia_desde DATE NULL,
    motivo_encerramento VARCHAR(30) NULL,
    valor_concedido NUMERIC(18,2) NULL,
    quantidade NUMERIC(18,4) NULL,
    unidade VARCHAR(50) NULL,
    data_hora_servico TIMESTAMPTZ NULL,
    unidade_servico VARCHAR(200) NULL,
    situacao VARCHAR(80) NULL,
    referencia_territorial_observacao_id BIGINT NULL REFERENCES silver.referencia_territorial_observacao(referencia_territorial_observacao_id),
    natureza_referencia_territorial VARCHAR(50) NULL,
    subprefeitura_referencia_id BIGINT NULL REFERENCES ref.subprefeitura(subprefeitura_id),
    distrito_referencia_id BIGINT NULL REFERENCES ref.distrito(distrito_id),
    source_as_of TIMESTAMPTZ NOT NULL,
    qc_resultado VARCHAR(30) NULL,
    qc_especifico_implementado BOOLEAN NOT NULL DEFAULT FALSE,
    vigencia_versao_inicio TIMESTAMPTZ NOT NULL,
    vigencia_versao_fim TIMESTAMPTZ NULL,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pg_serving_identidade CHECK(
        (estado_atribuicao_identidade='ATRIBUIDA' AND pessoa_uuid IS NOT NULL)
        OR (estado_atribuicao_identidade IN ('PENDENTE_IDENTIDADE','CONFLITO_IDENTIDADE') AND pessoa_uuid IS NULL)
    ),
    UNIQUE(registro_origem_id,versao_interna)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pg_serving_registro_vigente
    ON serving.registro_integrado(registro_origem_id) WHERE status_analitico='VIGENTE';

-- Evolui a tabela de rastreabilidade já criada pelo Resultado Core para receber o mesmo nível
-- de detalhe usado pelo Processor SQL Server.
ALTER TABLE ingestao.item_processado
    ADD COLUMN IF NOT EXISTS pessoa_origem_id BIGINT NULL REFERENCES silver.pessoa_origem(pessoa_origem_id),
    ADD COLUMN IF NOT EXISTS registro_origem_id BIGINT NULL REFERENCES silver.registro_origem(registro_origem_id),
    ADD COLUMN IF NOT EXISTS codigo_origem VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS versao_interna INTEGER NULL,
    ADD COLUMN IF NOT EXISTS conteudo_hash CHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS data_referencia TIMESTAMPTZ NULL;

CREATE INDEX IF NOT EXISTS ix_pg_item_processado_origem
    ON ingestao.item_processado(lote_id,classe_item,codigo_origem);
