<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <ProjectReference Include="..\Jornada.Operational.Sql\Jornada.Operational.Sql.csproj" />
    <ProjectReference Include="..\Jornada.Contracts\Jornada.Contracts.csproj" />
    <ProjectReference Include="..\Jornada.Bronze.Storage\Jornada.Bronze.Storage.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
  </ItemGroup>
</Project>
