<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Jornada.Bronze.Storage\Jornada.Bronze.Storage.csproj" />
    <ProjectReference Include="..\Jornada.Contracts\Jornada.Contracts.csproj" />
    <ProjectReference Include="..\Jornada.Ingestion\Jornada.Ingestion.csproj" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>
</Project>
