<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Jornada.Operational.Sql\Jornada.Operational.Sql.csproj" />
    <PackageReference Include="Testcontainers.MsSql" Version="4.14.0" />
    <ProjectReference Include="..\..\src\Jornada.Bronze.Storage\Jornada.Bronze.Storage.csproj" />
    <ProjectReference Include="..\..\src\Jornada.Bronze.Maintenance.Worker\Jornada.Bronze.Maintenance.Worker.csproj" />
    <ProjectReference Include="..\..\src\Jornada.Operations.Maintenance.Worker\Jornada.Operations.Maintenance.Worker.csproj" />
    <ProjectReference Include="..\..\src\Jornada.Pipeline.Coordination\Jornada.Pipeline.Coordination.csproj" />
    <ProjectReference Include="..\..\src\Jornada.Contracts\Jornada.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Jornada.Api\Jornada.Api.csproj" />
    <ProjectReference Include="..\..\src\Jornada.Processor.Worker\Jornada.Processor.Worker.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.11" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
      <Using Include="NUnit.Framework" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\database\Jornada_Fase1.sql" Link="database\Jornada_Fase1.sql" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\database\Jornada_Seed_Dev.sql" Link="database\Jornada_Seed_Dev.sql" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\config\contracts\**\*.json" Link="config\contracts\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\config\security\authorization-matrix.json" Link="config\security\authorization-matrix.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\config\security\test-access-keys.json" Link="config\security\test-access-keys.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\config\observability\metrics-slo-catalog.json" Link="config\observability\metrics-slo-catalog.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\openapi\jornada-v1.openapi.json" Link="openapi\jornada-v1.openapi.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../fixtures/**/*" CopyToOutputDirectory="PreserveNewest" Link="fixtures/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
