[global]
   workgroup = WORKGROUP
   server role = standalone server
   map to guest = Bad User
   server min protocol = SMB2
   smb ports = 445
   disable spoolss = yes
   load printers = no
   printing = bsd
   printcap name = /dev/null

[bronze]
   path = /srv/jornada/bronze
   browseable = yes
   writable = yes
   guest ok = yes
   read only = no
   force user = root
   create mask = 0666
   directory mask = 0777
