<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <ProjectReference Include="..\Jornada.Operational.Sql\Jornada.Operational.Sql.csproj" />
    <ProjectReference Include="..\Jornada.Pipeline.Coordination\Jornada.Pipeline.Coordination.csproj" />
    <ProjectReference Include="..\Jornada.Contracts\Jornada.Contracts.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.3" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\data\reference\ibge-nomes-2022\**\*"
          Link="data\reference\ibge-nomes-2022\%(RecursiveDir)%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
