namespace Jornada.Tests.Unit;

[TestFixture]
[Category("Unit")]
public sealed class DevTestConsoleContractTests
{
    private static string Root()
    {
        var d=new DirectoryInfo(TestContext.CurrentContext.TestDirectory);
        while(d is not null&&!Directory.Exists(Path.Combine(d.FullName,"Solution")))d=d.Parent;
        return d?.FullName??throw new DirectoryNotFoundException();
    }

    [Test]
    public void Console_has_live_terminal_session_history_manual_zip_and_real_local_infrastructure()
    {
        var root=Root();
        var program=File.ReadAllText(Path.Combine(root,"Solution","src","Jornada.DevConsole","Program.cs"));
        var runtime=File.ReadAllText(Path.Combine(root,"Solution","src","Jornada.DevConsole","DevConsoleRuntime.cs"));
        var page=File.ReadAllText(Path.Combine(root,"Solution","src","Jornada.DevConsole","Page.cs"));
        var friendlyHtml=File.ReadAllText(Path.Combine(root,"Solution","src","Jornada.DevConsole","FriendlyJsonHtml.cs"));
        var infraScript=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-infrastructure.ps1"));
        var opsScript=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-operations.ps1"));
        var goldScript=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-gold-synthetic.ps1"));
        var localDb=File.ReadAllText(Path.Combine(root,"Solution","scripts","local-db.ps1"));
        var bootstrap=File.ReadAllText(Path.Combine(root,"Solution","teste.ps1"));
        var goldSql=File.ReadAllText(Path.Combine(root,"Solution","database","Jornada_Dev_GoldSynthetic.sql"));
        var bundleScript=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-contract-bundle.ps1"));
        var initialConfigScript=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-initial-config.ps1"));
        var localCluster=File.ReadAllText(Path.Combine(root,"Solution","scripts","local-cluster.ps1"));
        var devEnv=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-env.ps1"));
        var compose=File.ReadAllText(Path.Combine(root,"Solution","docker-compose.yml"));
        var clusterConfig=File.ReadAllText(Path.Combine(root,"Solution","install","windows-production","Jornada.Cluster.Test.json"));
        var entrypoint=File.ReadAllText(Path.Combine(root,"Solution","install","container-test","entrypoint.sh"));

        Assert.Multiple(()=>{
            Assert.That(program,Does.Contain("/api/commands/{command}/start"));
            Assert.That(program,Does.Contain("/api/runs/{id:guid}/stream"));
            Assert.That(program,Does.Contain("ListSessionSummariesAsync(ct)"));
            Assert.That(program,Does.Contain("text/event-stream"));
            Assert.That(program,Does.Contain("/api/runs/{id:guid}/result"));
            Assert.That(program,Does.Contain("/api/zip/manual/start"));
            Assert.That(program,Does.Contain("/api/zip/template"));
            Assert.That(program,Does.Contain("/api/runs/{id:guid}/result/html"));
            Assert.That(program,Does.Contain("/api/runs/{id:guid}/artifacts/{index:int}"));
            Assert.That(program,Does.Contain("/api/semiblind/template"));
            Assert.That(program,Does.Contain("/api/semiblind/search"));
            Assert.That(program,Does.Contain("/api/contracts/file"));
            Assert.That(program,Does.Contain("ContractFileService"));
            Assert.That(program,Does.Contain("ActiveConfigFileService"));
            Assert.That(program,Does.Contain("/api/config/active/file"));
            Assert.That(program,Does.Contain("FriendlyJsonHtml.Render"));
            Assert.That(friendlyHtml,Does.Contain(".grid{display:grid"));
            Assert.That(friendlyHtml,Does.Contain(".table-wrap{overflow:auto"));
            Assert.That(friendlyHtml,Does.Contain("Exibindo "));
            Assert.That(friendlyHtml,Does.Contain("ID do modelo"));
            Assert.That(friendlyHtml,Does.Contain("UUID da pessoa"));
            Assert.That(friendlyHtml,Does.Not.Contain("<pre>"));

            Assert.That(runtime,Does.Contain("LiveExecutionService"));
            Assert.That(runtime,Does.Contain("ReadLineAsync"));
            Assert.That(runtime,Does.Contain("live.Add(\"stdout\""));
            Assert.That(runtime,Does.Contain("live.Add(\"stderr\""));
            Assert.That(runtime,Does.Contain("dev-console-infrastructure.ps1 -Action up"));
            Assert.That(runtime,Does.Contain("dev-console-infrastructure.ps1 -Action clean"));
            Assert.That(runtime,Does.Not.Contain("update-build"));
            Assert.That(runtime,Does.Not.Contain("Comando real ainda não mapeado."));
            Assert.That(runtime,Does.Contain("dev-console-gold-synthetic.ps1"));
            Assert.That(runtime,Does.Contain("build-ingestion-fixture.py"));
            Assert.That(runtime,Does.Contain("Gerar e enviar ZIP de ingestão"));
            Assert.That(runtime,Does.Contain("Ver/alterar contratos de ingestão"));
            Assert.That(runtime,Does.Contain("Ver/editar configurações ativas"));
            Assert.That(runtime.IndexOf("contract-editor",StringComparison.Ordinal),Is.LessThan(runtime.IndexOf("new(\"zip\"",StringComparison.Ordinal)));
            Assert.That(runtime,Does.Contain("-ZipPath"));
            Assert.That(runtime,Does.Contain("manual-zip"));
            Assert.That(runtime,Does.Contain("sessionStartedAt=DateTimeOffset.UtcNow"));
            Assert.That(runtime,Does.Contain("Where(x=>x.StartedAt>=sessionStartedAt)"));
            Assert.That(runtime,Does.Contain("JsonSerializerDefaults.Web"));
            Assert.That(runtime,Does.Contain("JsonSerializer.Serialize(item,StreamJson)"));
            Assert.That(runtime,Does.Contain("StandardOutputEncoding=Encoding.UTF8"));
            Assert.That(runtime,Does.Contain("StandardErrorEncoding=Encoding.UTF8"));
            Assert.That(runtime,Does.Contain("result.ExitCode==0&&candidatePath is not null&&File.Exists(candidatePath)"));
            Assert.That(runtime,Does.Contain("catch(JsonException)"));
            Assert.That(runtime,Does.Contain("ListSummariesAsync"));
            Assert.That(runtime,Does.Contain("ListSessionSummariesAsync"));
            Assert.That(runtime,Does.Contain("(await ListSessionSummariesAsync(ct))"));
            Assert.That(runtime,Does.Contain("HeartbeatAsync"));
            Assert.That(runtime,Does.Contain("Processo ativo há"));
            Assert.That(runtime,Does.Contain("\"environment-status\""));
            Assert.That(runtime,Does.Contain("Status/health da infraestrutura"));
            Assert.That(runtime,Does.Contain(".Take(200)"));
            Assert.That(runtime,Does.Contain("summariesRoot"));
            Assert.That(runtime,Does.Contain("ReadLegacySummaryAsync"));
            Assert.That(runtime,Does.Contain("Path.GetExtension(path)"));
            Assert.That(runtime,Does.Contain("!string.Equals(Path.GetExtension(path),\".json\""));

            Assert.That(page,Does.Contain("🕘 Execuções"));
            Assert.That(page,Does.Contain("Console DEV / Comandos"));
            Assert.That(page,Does.Contain("Execução / "));
            Assert.That(page,Does.Contain("const breadcrumb=document.getElementById('breadcrumb')"));
            Assert.That(page,Does.Contain("item.stream??item.Stream??'system'"));
            Assert.That(page,Does.Contain("item.at??item.At??new Date().toISOString()"));
            Assert.That(page,Does.Contain("Number.isNaN(parsed.getTime())"));
            Assert.That(page,Does.Contain("(item.stream??item.Stream)==='status'"));
            Assert.That(page,Does.Contain("console-shell"));
            Assert.That(page,Does.Contain("RODANDO..."));
            Assert.That(page,Does.Contain("new EventSource"));
            Assert.That(page,Does.Contain("Execuções desta sessão"));
            Assert.That(page,Does.Contain("A lista começa vazia a cada inicialização da Console DEV"));
            Assert.That(page,Does.Not.Contain("O histórico é persistido entre reinicializações da Console DEV."));
            Assert.That(page,Does.Contain("Entrada manual para o ZIP"));
            Assert.That(page,Does.Contain("Gerar e enviar"));
            Assert.That(page,Does.Contain("manifest.json"));
            Assert.That(page,Does.Contain("pessoas.jsonl"));
            Assert.That(page,Does.Contain("registros.jsonl"));
            Assert.That(page,Does.Contain("Versão Pessoa utilizável"));
            Assert.That(page,Does.Contain("zipPessoaSchemaVersao.value=t.pessoaSchemaVersao"));
            Assert.That(page,Does.Contain("pessoaSchemaVersao:Number(zipPessoaSchemaVersao.value)"));
            Assert.That(page,Does.Not.Contain("pessoaSchemaVersao:5"));
            Assert.That(page,Does.Contain("Resultado salvo em:"));
            Assert.That(page,Does.Contain("Ver dados do resultado"));
            Assert.That(page,Does.Contain("Executar novamente"));
            Assert.That(page,Does.Contain("Falha ao carregar o histórico."));
            Assert.That(page,Does.Contain("historyList.textContent=\'Carregando...\'"));
            Assert.That(page,Does.Contain("const historyList=document.getElementById('history')"));
            Assert.That(page,Does.Contain("AbortController"));
            Assert.That(page,Does.Contain("excedeu 7 segundos"));

            Assert.That(localDb,Does.Contain("iniciando Docker Desktop"));
            Assert.That(localDb,Does.Contain("Start-Process -FilePath $dockerDesktopPath"));
            Assert.That(localDb,Does.Contain("Aguardando Docker Engine"));
            Assert.That(localDb,Does.Contain("Docker Engine pronto"));
            Assert.That(runtime,Does.Contain("SQL Server, schema, NAS, referência IBGE, NODE1/NODE2 e garante o modelo BOOTSTRAP inicial ATIVO"));
            Assert.That(runtime,Does.Contain("Environment.SpecialFolder.LocalApplicationData"));
            Assert.That(runtime,Does.Contain("Path.Combine(local,\"Jornada\",\"DevConsole\")"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action system-status"));
            Assert.That(runtime,Does.Contain("Estado geral do sistema"));
            Assert.That(runtime,Does.Not.Contain("new(\"reference-check\",\"Validar referência IBGE\""));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action ingest-latest"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action pipeline-status"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action blocking"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action calibrate"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action linkage"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action replay-latest"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action report"));
            Assert.That(runtime,Does.Not.Contain("Garantir modelo bootstrap inicial (IBGE)"));
            Assert.That(runtime,Does.Not.Contain("dev-console-operations.ps1 -Action calibrate-initial"));
            Assert.That(runtime,Does.Contain("Gerar bundle de contratos e configurações"));
            Assert.That(runtime,Does.Contain("dev-console-contract-bundle.ps1"));
            Assert.That(runtime,Does.Contain("Dependencies"));
            Assert.That(runtime,Does.Contain("DependencyNote"));
            Assert.That(runtime,Does.Contain("GoldZipTemplateService"));
            Assert.That(runtime,Does.Contain("FROM gold.pessoa"));
            Assert.That(runtime,Does.Contain("gpv.status IN('ATIVA','ENCERRADA')"));
            Assert.That(runtime,Does.Contain("[\"pessoaSchemaVersao\"]=pessoaSchemaVersao"));
            Assert.That(runtime,Does.Not.Contain("[\"pessoaSchemaVersao\"]=5"));
            Assert.That(runtime,Does.Not.Contain("new(\"initial-config\""));
            Assert.That(runtime,Does.Not.Contain("Gerar/ver configuração inicial"));
            Assert.That(runtime,Does.Contain("ARTEFATO:"));
            Assert.That(runtime,Does.Contain("Consulta semicega"));
            Assert.That(runtime,Does.Contain("SemiblindDevService"));
            Assert.That(runtime,Does.Contain("JornadaSyntheticDev"));
            Assert.That(runtime,Does.Contain("Não existe fallback para Gold real."));

            Assert.That(goldScript,Does.Contain("gold-synthetic-records.json"));
            Assert.That(goldScript,Does.Contain("[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)"));
            Assert.That(goldScript,Does.Contain("$PSStyle.OutputRendering='PlainText'"));
            Assert.That(goldScript,Does.Contain("SCALE_PEOPLE=30000"));
            Assert.That(goldScript,Does.Contain("Jornada_Dev_SyntheticScale_Diversify.sql"));
            Assert.That(goldScript,Does.Contain("population-profile','demographic-primary"));
            Assert.That(goldScript,Does.Contain("birth_daily_sp_projection2024_2026.json"));
            Assert.That(goldScript,Does.Not.Contain("-y 0"));
            Assert.That(goldScript,Does.Not.Contain("Jornada_Dev_LinkageValidation.sql"));
            Assert.That(goldScript,Does.Not.Contain("Jornada_Dev_GoldSynthetic.sql"));
            Assert.That(goldSql,Does.Contain("SET QUOTED_IDENTIFIER ON;"));
            Assert.That(goldSql,Does.Contain("SET ANSI_NULLS ON;"));
            Assert.That(goldSql,Does.Contain("SET ANSI_WARNINGS ON;"));
            Assert.That(goldSql,Does.Contain("SET ARITHABORT ON;"));
            Assert.That(goldSql,Does.Contain("SET CONCAT_NULL_YIELDS_NULL ON;"));
            Assert.That(goldSql,Does.Contain("SET NUMERIC_ROUNDABORT OFF;"));
            Assert.That(infraScript,Does.Contain("local-cluster.ps1"));
            Assert.That(infraScript,Does.Contain("-NoBuild"));
            Assert.That(infraScript,Does.Contain("jornada-reference-bootstrap"));
            Assert.That(opsScript,Does.Contain("local-check-ibge-reference.ps1"));
            Assert.That(opsScript,Does.Contain("Jornada.Bronze.Verify"));
            Assert.That(opsScript,Does.Contain("jornada.ingestao.write"));
            Assert.That(opsScript,Does.Contain("Ensure-ClusterRunning"));
            Assert.That(opsScript,Does.Contain("local-cluster.ps1"));
            Assert.That(opsScript,Does.Contain("calibrate-initial"));
            Assert.That(opsScript,Does.Contain("Gold sintética completa de 30.000 pessoas"));
            Assert.That(opsScript,Does.Contain("contract-config-bundle.zip"));
            Assert.That(opsScript,Does.Contain("NAO_ENCONTRADA_NO_AMBIENTE_ATUAL"));
            Assert.That(opsScript,Does.Contain("staleReceipt=$true"));
            Assert.That(opsScript,Does.Contain("O seed fixo não libera linkage"));
            Assert.That(opsScript,Does.Contain("Subir infraestrutura, referências e bootstrap"));
            Assert.That(opsScript,Does.Not.Contain("Execute 'Garantir modelo bootstrap inicial (IBGE)'"));
            Assert.That(opsScript,Does.Contain("[string]$ZipPath"));
            Assert.That(opsScript,Does.Contain("ZipPath deve apontar para um ZIP gerado pela Console DEV"));
            Assert.That(opsScript,Does.Contain("CREATED_AND_ACTIVATED_BOOTSTRAP"));
            Assert.That(opsScript,Does.Contain("SEED_DEV_FIXO_NAO_TREINADO"));
            Assert.That(bundleScript,Does.Contain("JORNADA_DEV_CONTRACT_CONFIG_V1"));
            Assert.That(bundleScript,Does.Contain("config/contracts"));
            Assert.That(bundleScript,Does.Contain("openapi/jornada-v1.openapi.json"));
            Assert.That(bundleScript,Does.Contain("MANIFEST.sha256"));
            Assert.That(bundleScript,Does.Contain("Nenhum modelo ATIVO"));
            Assert.That(bundleScript,Does.Contain("Subir infraestrutura, referências e bootstrap"));
            Assert.That(bundleScript,Does.Not.Contain("Garantir modelo bootstrap inicial (IBGE)"));
            Assert.That(bundleScript,Does.Contain("SEED_DEV_FIXO_NAO_TREINADO"));
            Assert.That(bundleScript,Does.Contain("BUNDLE_INFO.html"));
            Assert.That(bundleScript,Does.Contain("Conteúdo incluído"));
            Assert.That(bundleScript,Does.Contain("Fingerprint SHA-256"));
            Assert.That(bundleScript,Does.Not.Contain("<pre>$escapedInfo</pre>"));
            Assert.That(bundleScript,Does.Contain("function ConvertTo-HtmlEncodedText"));
            Assert.That(bundleScript,Does.Not.Contain("function H([object]$Value)"));
            Assert.That(bundleScript,Does.Contain("ARTEFATO: $ZipPath"));
            Assert.That(initialConfigScript,Does.Contain("configuration.json"));
            Assert.That(initialConfigScript,Does.Contain("configuration.html"));
            Assert.That(initialConfigScript,Does.Contain("ARTEFATO: $jsonPath"));
            Assert.That(initialConfigScript,Does.Contain("runtimeHealth=$health"));
            Assert.That(initialConfigScript,Does.Contain("activeLinkageModel=$modelState"));
            Assert.That(initialConfigScript,Does.Contain("modelo BOOTSTRAP inicial ATIVO"));
            Assert.That(initialConfigScript,Does.Contain("Resumo de status/health"));
            Assert.That(initialConfigScript,Does.Contain("Modelo de linkage ativo"));
            Assert.That(initialConfigScript,Does.Contain("Status dos serviços no momento da geração"));
            Assert.That(initialConfigScript,Does.Not.Contain("<pre>$escaped</pre>"));
            Assert.That(initialConfigScript,Does.Contain("function ConvertTo-HtmlEncodedText"));
            Assert.That(initialConfigScript,Does.Not.Contain("function H([object]$Value)"));
            Assert.That(infraScript,Does.Contain("dev-console-initial-config.ps1"));
            Assert.That(infraScript,Does.Contain("dev-console-operations.ps1"));
            Assert.That(infraScript,Does.Contain("-Action calibrate-initial"));
            Assert.That(infraScript,Does.Contain("modelo BOOTSTRAP inicial ATIVO"));
            Assert.That(infraScript,Does.Contain("Estado transitório da Console removido"));
            Assert.That(infraScript,Does.Contain("Histórico de execuções foi preservado"));
            Assert.That(localCluster,Does.Contain("[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)"));
            Assert.That(localCluster,Does.Contain("Etapa cluster 1/6"));
            Assert.That(localCluster,Does.Contain("Show-ComposeFailureDiagnostics"));
            Assert.That(localCluster,Does.Contain("$composeExitCode=$LASTEXITCODE"));
            Assert.That(localCluster,Does.Contain("LOCAL_CLUSTER_TEST_DOSSIER"));
            Assert.That(localCluster,Does.Contain("sp_registrar_dossie_decisao_modelo_linkage"));
            Assert.That(localCluster,Does.Contain("@acao=N'VALIDATE'"));
            Assert.That(localCluster,Does.Contain("@acao=N'ACTIVATE'"));
            Assert.That(localCluster,Does.Contain("Gate DT-15 DEV preparado para VALIDATE"));
            Assert.That(localCluster,Does.Contain("Gate DT-15 DEV preparado para ACTIVATE"));
            Assert.That(localCluster,Does.Contain("Logs do jornada-reference-bootstrap"));
            Assert.That(localCluster,Does.Contain("Ensure-SyntheticIbgeIdentityText"));
            Assert.That(localCluster,Does.Contain("Pessoa Teste %"));
            Assert.That(localCluster,Does.Contain("Jornada_Dev_SyntheticScale_Diversify.sql"));
            Assert.That(localCluster,Does.Contain("nomes/nome da mãe amostrados pela frequência IBGE"));
            Assert.That(opsScript,Does.Contain("[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)"));
            Assert.That(opsScript,Does.Contain("[string[]]$ComposeArgs"));
            Assert.That(opsScript,Does.Contain("@ComposeArgs"));
            Assert.That(opsScript,Does.Contain("Invoke-Compose exige um subcomando"));
            Assert.That(opsScript,Does.Contain("'system-status'"));
            Assert.That(opsScript,Does.Contain("ESTADO GERAL: OK"));
            Assert.That(opsScript,Does.Contain("Jornada.Linkage.Runner.dll"));
            Assert.That(opsScript,Does.Not.Contain("[string[]]$Args"));
            Assert.That(opsScript,Does.Contain("--mode','REPLAY"));
            Assert.That(page,Does.Contain("A tela mostra somente operações reais"));
            Assert.That(page,Does.Contain("Pré-requisitos:"));
            Assert.That(page,Does.Contain("dependencyNote"));
            Assert.That(page,Does.Contain("Formulário HTML"));
            Assert.That(page,Does.Contain("JSON / JSONL"));
            Assert.That(page,Does.Contain("Atualizar exemplo da Gold"));
            Assert.That(page,Does.Contain("Visualização amigável"));
            Assert.That(page,Does.Not.Contain("Visualizar JSON em HTML"));
            Assert.That(page,Does.Contain("Arquivos gerados:"));
            Assert.That(page,Does.Contain("Consulta semicega · DEV sintético"));
            Assert.That(page,Does.Contain("Contratos de ingestão"));
            Assert.That(page,Does.Contain("Validar e salvar"));
            Assert.That(page,Does.Contain("openContractDialog()"));
            Assert.That(page,Does.Contain("Configurações JSON ativas"));
            Assert.That(page,Does.Contain("Visualização amigável"));
            Assert.That(page,Does.Contain("Arquivo fonte:"));
            Assert.That(page,Does.Contain("Runtime:"));
            Assert.That(page,Does.Contain("openActiveConfigDialog()"));
            Assert.That(page,Does.Contain("Usar exemplo da Gold sintética"));
            Assert.That(devEnv,Does.Contain("JornadaSyntheticDev"));
            Assert.That(devEnv,Does.Contain("JORNADA_LOCAL_SYNTHETIC_PEOPLE"));
            Assert.That(devEnv,Does.Contain("30000"));
            Assert.That(compose,Does.Contain("SemiblindIdentitySearch__Enabled"));
            Assert.That(compose,Does.Contain("test-access-keys.json:/opt/jornada/config/security/test-access-keys.json:ro"));
            Assert.That(compose,Does.Contain("[reference-bootstrap] Iniciando ENSURE_NAME_FREQUENCY_SNAPSHOT"));
            Assert.That(compose,Does.Not.Contain("LinkageParameters__Operation=ENSURE_IBGE_NOMINAL_U_REFERENCE dotnet"));
            Assert.That(clusterConfig,Does.Contain("\"component\":\"LinkageRunner\""));
            Assert.That(clusterConfig,Does.Contain("\"nodes\":[\"NODE2\"]"));
            Assert.That(clusterConfig,Does.Contain("\"--mode\",\"INCREMENTAL\""));
            Assert.That(clusterConfig,Does.Contain("\"LinkageRunner__PollingSeconds\": \"5\""));
            Assert.That(entrypoint,Does.Contain("LinkageRunner) echo"));
            Assert.That(entrypoint,Does.Contain("while true; do"));
            Assert.That(clusterConfig,Does.Contain("DEV_RESIDENT_RUNNER"));
            Assert.That(entrypoint,Does.Contain("(.nodes // [])"));
            Assert.That(bootstrap,Does.Contain("restore $Solution --locked-mode"));
            Assert.That(bootstrap,Does.Contain("build $Solution --no-restore"));

            var launch=File.ReadAllText(Path.Combine(root,"Solution","Jornada.slnLaunch"));
            Assert.That(launch,Does.Contain("Jornada.DevConsole.csproj"));
            Assert.That(launch,Does.Contain("\"Action\": \"Start\""));

            Assert.That(program,Does.Not.Contain("Jornada.Api"));
        });
    }
}
