namespace Jornada.Tests.Unit;

[TestFixture]
[Category("Unit")]
public sealed class DevTestConsoleContractTests
{
    private static string Root()
    {
        var d=new DirectoryInfo(TestContext.CurrentContext.TestDirectory);
        while(d is not null&&!Directory.Exists(Path.Combine(d.FullName,"Solution")))d=d.Parent;
        return d?.FullName??throw new DirectoryNotFoundException();
    }

    [Test]
    public void Console_has_live_terminal_session_history_manual_zip_and_real_local_infrastructure()
    {
        var root=Root();
        var program=File.ReadAllText(Path.Combine(root,"Solution","src","Jornada.DevConsole","Program.cs"));
        var runtime=File.ReadAllText(Path.Combine(root,"Solution","src","Jornada.DevConsole","DevConsoleRuntime.cs"));
        var page=File.ReadAllText(Path.Combine(root,"Solution","src","Jornada.DevConsole","Page.cs"));
        var friendlyHtml=File.ReadAllText(Path.Combine(root,"Solution","src","Jornada.DevConsole","FriendlyJsonHtml.cs"));
        var infraScript=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-infrastructure.ps1"));
        var opsScript=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-operations.ps1"));
        var goldScript=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-gold-synthetic.ps1"));
        var goldAddScript=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-gold-add.ps1"));
        var localDb=File.ReadAllText(Path.Combine(root,"Solution","scripts","local-db.ps1"));
        var bootstrap=File.ReadAllText(Path.Combine(root,"Solution","teste.ps1"));
        var goldSql=File.ReadAllText(Path.Combine(root,"Solution","database","Jornada_Dev_GoldSynthetic.sql"));
        var bundleScript=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-contract-bundle.ps1"));
        var initialConfigScript=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-initial-config.ps1"));
        var htmlHelper=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-html.ps1"));
        var htmlHelperTest=File.ReadAllText(Path.Combine(root,"Solution","scripts","local-test-dev-console-html-encoding.ps1"));
        var localCluster=File.ReadAllText(Path.Combine(root,"Solution","scripts","local-cluster.ps1"));
        var devEnv=File.ReadAllText(Path.Combine(root,"Solution","scripts","dev-console-env.ps1"));
        var compose=File.ReadAllText(Path.Combine(root,"Solution","docker-compose.yml"));

        Assert.Multiple(()=>{
            Assert.That(program,Does.Contain("/api/commands/{command}/start"));
            Assert.That(program,Does.Contain("/api/runs/{id:guid}/stream"));
            Assert.That(program,Does.Contain("ListSessionSummariesAsync(ct)"));
            Assert.That(program,Does.Contain("text/event-stream"));
            Assert.That(program,Does.Contain("/api/runs/{id:guid}/result"));
            Assert.That(program,Does.Contain("/api/zip/manual/start"));
            Assert.That(program,Does.Contain("/api/zip/template"));
            Assert.That(program,Does.Contain("/api/runs/{id:guid}/result/html"));
            Assert.That(program,Does.Contain("/api/runs/{id:guid}/artifacts/{index:int}"));
            Assert.That(program,Does.Contain("/api/semiblind/template"));
            Assert.That(program,Does.Contain("/api/semiblind/search"));
            Assert.That(program,Does.Contain("/api/contracts/file"));
            Assert.That(program,Does.Contain("ContractFileService"));
            Assert.That(program,Does.Contain("ActiveConfigFileService"));
            Assert.That(program,Does.Contain("/api/config/active/file"));
            Assert.That(program,Does.Contain("FriendlyJsonHtml.Render"));
            Assert.That(friendlyHtml,Does.Contain(".grid{display:grid"));
            Assert.That(friendlyHtml,Does.Contain(".table-wrap{overflow:auto"));
            Assert.That(friendlyHtml,Does.Contain("Exibindo "));
            Assert.That(friendlyHtml,Does.Contain("ID do modelo"));
            Assert.That(friendlyHtml,Does.Contain("UUID da pessoa"));
            Assert.That(friendlyHtml,Does.Not.Contain("<pre>"));

            Assert.That(runtime,Does.Contain("LiveExecutionService"));
            Assert.That(runtime,Does.Contain("ReadLineAsync"));
            Assert.That(runtime,Does.Contain("live.Add(\"stdout\""));
            Assert.That(runtime,Does.Contain("live.Add(\"stderr\""));
            Assert.That(runtime,Does.Contain("dev-console-infrastructure.ps1 -Action up"));
            Assert.That(runtime,Does.Contain("dev-console-infrastructure.ps1 -Action clean"));
            Assert.That(runtime,Does.Not.Contain("update-build"));
            Assert.That(runtime,Does.Not.Contain("Comando real ainda não mapeado."));
            Assert.That(runtime,Does.Contain("dev-console-gold-add.ps1 -AdditionalPeople 5000"));
            Assert.That(runtime,Does.Contain("Adicionar mais 5.000 registros"));
            Assert.That(runtime,Does.Contain("0 → 5k → 10k"));
            Assert.That(runtime,Does.Contain("build-ingestion-fixture.py"));
            Assert.That(runtime,Does.Contain("new(\"zip\",\"Ingestão\""));
            Assert.That(runtime,Does.Contain("new(\"configuration\",\"Contratos e configurações\""));
            Assert.That(runtime,Does.Not.Contain("new(\"contract-editor\""));
            Assert.That(runtime,Does.Not.Contain("new(\"active-config-editor\""));
            Assert.That(runtime,Does.Contain("Visible=false"));
            Assert.That(program,Does.Contain("CommandCatalog.All.Where(x=>x.Visible)"));
            Assert.That(program,Does.Contain("\"zip\"=>counts.GetValueOrDefault(\"zip\")+counts.GetValueOrDefault(\"ingestion\")+counts.GetValueOrDefault(\"pipeline-status\")"));
            Assert.That(program,Does.Contain("\"linkage\"=>counts.GetValueOrDefault(\"linkage\")+counts.GetValueOrDefault(\"replay\")"));
            Assert.That(program,Does.Contain("\"gold-synthetic\"=>counts.GetValueOrDefault(\"gold-synthetic\")+counts.GetValueOrDefault(\"blocking\")"));
            Assert.That(program,Does.Contain("\"configuration\"=>counts.GetValueOrDefault(\"contract-bundle\")"));
            Assert.That(runtime.IndexOf("new(\"infrastructure\"",StringComparison.Ordinal),Is.LessThan(runtime.IndexOf("new(\"zip\"",StringComparison.Ordinal)));
            Assert.That(runtime.IndexOf("new(\"zip\"",StringComparison.Ordinal),Is.LessThan(runtime.IndexOf("new(\"semiblind\"",StringComparison.Ordinal)));
            Assert.That(runtime.IndexOf("new(\"semiblind\"",StringComparison.Ordinal),Is.LessThan(runtime.IndexOf("new(\"linkage\"",StringComparison.Ordinal)));
            Assert.That(runtime.IndexOf("new(\"linkage\"",StringComparison.Ordinal),Is.LessThan(runtime.IndexOf("new(\"configuration\"",StringComparison.Ordinal)));
            Assert.That(runtime.IndexOf("new(\"configuration\"",StringComparison.Ordinal),Is.LessThan(runtime.IndexOf("new(\"gold-synthetic\"",StringComparison.Ordinal)));
            Assert.That(runtime.IndexOf("new(\"gold-synthetic\"",StringComparison.Ordinal),Is.LessThan(runtime.IndexOf("new(\"calibration\"",StringComparison.Ordinal)));
            Assert.That(runtime.IndexOf("new(\"calibration\"",StringComparison.Ordinal),Is.LessThan(runtime.IndexOf("new(\"system-status\"",StringComparison.Ordinal)));
            Assert.That(runtime.IndexOf("new(\"system-status\"",StringComparison.Ordinal),Is.LessThan(runtime.IndexOf("new(\"finish\"",StringComparison.Ordinal)));
            Assert.That(runtime,Does.Contain("-ZipPath"));
            Assert.That(runtime,Does.Contain("manual-zip"));
            Assert.That(runtime,Does.Contain("sessionStartedAt=DateTimeOffset.UtcNow"));
            Assert.That(runtime,Does.Contain("Where(x=>x.StartedAt>=sessionStartedAt)"));
            Assert.That(runtime,Does.Contain("JsonSerializerDefaults.Web"));
            Assert.That(runtime,Does.Contain("JsonSerializer.Serialize(item,StreamJson)"));
            Assert.That(runtime,Does.Contain("StandardOutputEncoding=Encoding.UTF8"));
            Assert.That(runtime,Does.Contain("StandardErrorEncoding=Encoding.UTF8"));
            Assert.That(runtime,Does.Contain("result.ExitCode==0&&candidatePath is not null&&File.Exists(candidatePath)"));
            Assert.That(runtime,Does.Contain("catch(JsonException)"));
            Assert.That(runtime,Does.Contain("ListSummariesAsync"));
            Assert.That(runtime,Does.Contain("ListSessionSummariesAsync"));
            Assert.That(runtime,Does.Contain("(await ListSessionSummariesAsync(ct))"));
            Assert.That(runtime,Does.Contain("HeartbeatAsync"));
            Assert.That(runtime,Does.Contain("Processo ativo há"));
            Assert.That(runtime,Does.Not.Contain("\"environment-status\""));
            Assert.That(runtime,Does.Contain("infraestrutura/health"));
            Assert.That(opsScript,Does.Contain("[1/7] Status/health da infraestrutura"));
            Assert.That(opsScript,Does.Contain("dev-console-infrastructure.ps1') -Action status"));
            Assert.That(opsScript,Does.Contain("[6/7] Bronze"));
            Assert.That(opsScript,Does.Contain("Jornada.Bronze.Verify"));
            Assert.That(opsScript,Does.Contain("[7/7] Último linkage"));
            Assert.That(opsScript,Does.Contain("Diagnóstico do último linkage: NÃO APLICÁVEL"));
            Assert.That(opsScript,Does.Contain("Invoke-ClusterAction 'linkage-diagnose'"));
            Assert.That(runtime,Does.Contain(".Take(200)"));
            Assert.That(runtime,Does.Contain("summariesRoot"));
            Assert.That(runtime,Does.Contain("ReadLegacySummaryAsync"));
            Assert.That(runtime,Does.Contain("Path.GetExtension(path)"));
            Assert.That(runtime,Does.Contain("!string.Equals(Path.GetExtension(path),\".json\""));

            Assert.That(page,Does.Contain("🕘 Execuções"));
            Assert.That(page,Does.Contain("Console DEV / Comandos"));
            Assert.That(page,Does.Contain("Execução / "));
            Assert.That(page,Does.Contain("const breadcrumb=document.getElementById('breadcrumb')"));
            Assert.That(page,Does.Contain("item.stream??item.Stream??'system'"));
            Assert.That(page,Does.Contain("item.at??item.At??new Date().toISOString()"));
            Assert.That(page,Does.Contain("Number.isNaN(parsed.getTime())"));
            Assert.That(page,Does.Contain("(item.stream??item.Stream)==='status'"));
            Assert.That(page,Does.Contain("console-shell"));
            Assert.That(page,Does.Contain("RODANDO..."));
            Assert.That(page,Does.Contain("new EventSource"));
            Assert.That(page,Does.Contain("Execuções desta sessão"));
            Assert.That(page,Does.Contain("A lista começa vazia a cada inicialização da Console DEV"));
            Assert.That(page,Does.Not.Contain("O histórico é persistido entre reinicializações da Console DEV."));
            Assert.That(page,Does.Contain("Entrada manual para o ZIP"));
            Assert.That(page,Does.Contain("Gerar e enviar"));
            Assert.That(page,Does.Contain("Nova ingestão"));
            Assert.That(page,Does.Contain("Reenviar último"));
            Assert.That(page,Does.Contain("pipeline-status"));
            Assert.That(page,Does.Contain("Ver status da última ingestão"));
            Assert.That(page,Does.Contain("Executar replay do último run"));
            Assert.That(page,Does.Contain("Reconstruir blocking"));
            Assert.That(page,Does.Contain("Contratos e configurações"));
            Assert.That(page,Does.Contain("openConfigurationDialog()"));
            Assert.That(page,Does.Contain("Gerar bundle"));
            Assert.That(page,Does.Not.Contain(">SECRETARIA<"));
            Assert.That(page,Does.Not.Contain(">SISTEMA<"));
            Assert.That(page,Does.Contain("manifest.json"));
            Assert.That(page,Does.Contain("pessoas.jsonl"));
            Assert.That(page,Does.Contain("registros.jsonl"));
            Assert.That(page,Does.Contain("Versão Pessoa utilizável"));
            Assert.That(page,Does.Contain("zipPessoaSchemaVersao.value=t.pessoaSchemaVersao"));
            Assert.That(page,Does.Contain("pessoaSchemaVersao:Number(zipPessoaSchemaVersao.value)"));
            Assert.That(page,Does.Not.Contain("pessoaSchemaVersao:5"));
            Assert.That(page,Does.Contain("Resultado salvo em:"));
            Assert.That(page,Does.Contain("Ver dados do resultado"));
            Assert.That(page,Does.Contain("Executar novamente"));
            Assert.That(page,Does.Contain("Falha ao carregar o histórico."));
            Assert.That(page,Does.Contain("historyList.textContent=\'Carregando...\'"));
            Assert.That(page,Does.Contain("const historyList=document.getElementById('history')"));
            Assert.That(page,Does.Contain("AbortController"));
            Assert.That(page,Does.Contain("excedeu 7 segundos"));

            Assert.That(localDb,Does.Contain("iniciando Docker Desktop"));
            Assert.That(localDb,Does.Contain("Start-Process -FilePath $dockerDesktopPath"));
            Assert.That(localDb,Does.Contain("Aguardando Docker Engine"));
            Assert.That(localDb,Does.Contain("Docker Engine pronto"));
            Assert.That(runtime,Does.Contain("modelo BOOTSTRAP inicial ATIVO, configuração inicial e bundle de contratos/configurações"));
            Assert.That(runtime,Does.Contain("a preparação garante o modelo BOOTSTRAP ATIVO e descarta o corpus usado exclusivamente na calibração."));
            Assert.That(runtime,Does.Contain("gerar deliberadamente uma nova versão após alterar massa/parâmetros"));
            Assert.That(runtime,Does.Contain("Environment.SpecialFolder.LocalApplicationData"));
            Assert.That(runtime,Does.Contain("Path.Combine(local,\"Jornada\",\"DevConsole\")"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action system-status"));
            Assert.That(runtime,Does.Contain("Estado geral do sistema"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action ingest-latest"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action pipeline-status"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action blocking"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action calibrate"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action linkage"));
            Assert.That(runtime,Does.Contain("dev-console-operations.ps1 -Action replay-latest"));
            Assert.That(runtime,Does.Not.Contain("new(\"report\""));
            Assert.That(runtime,Does.Not.Contain("Garantir modelo bootstrap inicial (IBGE)"));
            Assert.That(runtime,Does.Not.Contain("dev-console-operations.ps1 -Action calibrate-initial"));
            Assert.That(runtime,Does.Contain("Gerar bundle de contratos e configurações"));
            Assert.That(runtime,Does.Contain("dev-console-contract-bundle.ps1"));
            Assert.That(runtime,Does.Contain("Dependencies"));
            Assert.That(runtime,Does.Contain("DependencyNote"));
            Assert.That(runtime,Does.Contain("GoldZipTemplateService"));
            Assert.That(runtime,Does.Contain("FROM gold.pessoa"));
            Assert.That(runtime,Does.Contain("gpv.status IN('ATIVA','ENCERRADA')"));
            Assert.That(runtime,Does.Contain("[\"pessoaSchemaVersao\"]=pessoaSchemaVersao"));
            Assert.That(runtime,Does.Not.Contain("[\"pessoaSchemaVersao\"]=5"));
            Assert.That(runtime,Does.Not.Contain("new(\"initial-config\""));
            Assert.That(runtime,Does.Not.Contain("Gerar/ver configuração inicial"));
            Assert.That(runtime,Does.Contain("ARTEFATO:"));
            Assert.That(runtime,Does.Contain("Consulta semicega"));
            Assert.That(runtime,Does.Contain("SemiblindDevService"));
            Assert.That(runtime,Does.Contain("JornadaSyntheticDev"));
            Assert.That(runtime,Does.Contain("A carga incremental reconstrói o blocking automaticamente."));

            Assert.That(goldScript,Does.Contain("gold-synthetic-records.json"));
            Assert.That(goldScript,Does.Contain("[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)"));
            Assert.That(goldScript,Does.Contain("$PSStyle.OutputRendering='PlainText'"));
            Assert.That(goldScript,Does.Contain("SCALE_PEOPLE=30000"));
            Assert.That(goldScript,Does.Contain("Jornada_Dev_SyntheticScale_Diversify.sql"));
            Assert.That(goldScript,Does.Contain("population-profile','demographic-primary"));
            Assert.That(goldScript,Does.Contain("birth_daily_sp_projection2024_2026.json"));
            Assert.That(goldScript,Does.Not.Contain("-y 0"));
            Assert.That(goldScript,Does.Not.Contain("Jornada_Dev_LinkageValidation.sql"));
            Assert.That(goldScript,Does.Not.Contain("Jornada_Dev_GoldSynthetic.sql"));
            Assert.That(goldScript,Does.Contain("Docker Desktop/Engine não está em execução"));
            Assert.That(goldAddScript,Does.Contain("[int]$AdditionalPeople=5000"));
            Assert.That(goldAddScript,Does.Contain("$target=$before+$AdditionalPeople"));
            Assert.That(goldAddScript,Does.Contain("SCALE_INCREMENTAL"));
            Assert.That(goldAddScript,Does.Contain("Jornada_Dev_SyntheticScale_Diversify.sql"));
            Assert.That(goldAddScript,Does.Contain("-Action blocking"));
            Assert.That(goldAddScript,Does.Contain("Gold sintética expandida de $before para $after"));
            Assert.That(goldSql,Does.Contain("SET QUOTED_IDENTIFIER ON;"));
            Assert.That(goldSql,Does.Contain("SET ANSI_NULLS ON;"));
            Assert.That(goldSql,Does.Contain("SET ANSI_WARNINGS ON;"));
            Assert.That(goldSql,Does.Contain("SET ARITHABORT ON;"));
            Assert.That(goldSql,Does.Contain("SET CONCAT_NULL_YIELDS_NULL ON;"));
            Assert.That(goldSql,Does.Contain("SET NUMERIC_ROUNDABORT OFF;"));
            Assert.That(infraScript,Does.Contain("local-cluster.ps1"));
            Assert.That(infraScript,Does.Contain("-NoBuild"));
            Assert.That(infraScript,Does.Contain("jornada-reference-bootstrap"));
            Assert.That(opsScript,Does.Contain("local-check-ibge-reference.ps1"));
            Assert.That(opsScript,Does.Contain("Jornada.Bronze.Verify"));
            Assert.That(opsScript,Does.Contain("jornada.ingestao.write"));
            Assert.That(opsScript,Does.Contain("Ensure-ClusterRunning"));
            Assert.That(opsScript,Does.Contain("local-cluster.ps1"));
            Assert.That(opsScript,Does.Contain("calibrate-initial"));
            Assert.That(opsScript,Does.Contain("Gold sintética completa de 30.000 pessoas"));
            Assert.That(opsScript,Does.Contain("Jornada.BootstrapCorpusLifecycle"));
            Assert.That(opsScript,Does.Contain("PENDING_DISCARD"));
            Assert.That(opsScript,Does.Contain("bootstrap-corpus-lifecycle.ps1"));
            Assert.That(opsScript,Does.Contain("operationalScalePeopleAfterBootstrap"));
            Assert.That(opsScript,Does.Contain("contract-config-bundle.zip"));
            Assert.That(opsScript,Does.Contain("NAO_ENCONTRADA_NO_AMBIENTE_ATUAL"));
            Assert.That(opsScript,Does.Contain("staleReceipt=$true"));
            Assert.That(opsScript,Does.Contain("O seed fixo não libera linkage"));
            Assert.That(opsScript,Does.Contain("Subir infraestrutura, referências e bootstrap"));
            Assert.That(opsScript,Does.Not.Contain("Execute 'Garantir modelo bootstrap inicial (IBGE)'"));
            Assert.That(opsScript,Does.Contain("[string]$ZipPath"));
            Assert.That(opsScript,Does.Contain("ZipPath deve apontar para um ZIP gerado pela Console DEV"));
            Assert.That(opsScript,Does.Contain("CREATED_AND_ACTIVATED_BOOTSTRAP"));
            Assert.That(opsScript,Does.Contain("SEED_DEV_FIXO_NAO_TREINADO"));
            Assert.That(bundleScript,Does.Contain("JORNADA_DEV_CONTRACT_CONFIG_V1"));
            Assert.That(bundleScript,Does.Contain("config/contracts"));
            Assert.That(bundleScript,Does.Contain("openapi/jornada-v1.openapi.json"));
            Assert.That(bundleScript,Does.Contain("MANIFEST.sha256"));
            Assert.That(bundleScript,Does.Contain("Nenhum modelo ATIVO"));
            Assert.That(bundleScript,Does.Contain("Subir infraestrutura, referências e bootstrap"));
            Assert.That(bundleScript,Does.Not.Contain("Garantir modelo bootstrap inicial (IBGE)"));
            Assert.That(bundleScript,Does.Contain("SEED_DEV_FIXO_NAO_TREINADO"));
            Assert.That(bundleScript,Does.Contain("BUNDLE_INFO.html"));
            Assert.That(bundleScript,Does.Contain("Conteúdo incluído"));
            Assert.That(bundleScript,Does.Contain("Fingerprint SHA-256"));
            Assert.That(bundleScript,Does.Not.Contain("<pre>$escapedInfo</pre>"));
            Assert.That(bundleScript,Does.Contain("dev-console-html.ps1"));
            Assert.That(bundleScript,Does.Contain("ConvertTo-DevConsoleHtmlText"));
            Assert.That(bundleScript,Does.Not.Contain("function ConvertTo-HtmlEncodedText"));
            Assert.That(bundleScript,Does.Not.Contain("function H([object]$Value)"));
            Assert.That(bundleScript,Does.Not.Contain("$(H "));
            Assert.That(bundleScript,Does.Contain("ARTEFATO: $ZipPath"));
            Assert.That(initialConfigScript,Does.Contain("configuration.json"));
            Assert.That(initialConfigScript,Does.Contain("configuration.html"));
            Assert.That(initialConfigScript,Does.Contain("ARTEFATO: $jsonPath"));
            Assert.That(initialConfigScript,Does.Contain("runtimeHealth=$health"));
            Assert.That(initialConfigScript,Does.Contain("activeLinkageModel=$modelState"));
            Assert.That(initialConfigScript,Does.Contain("modelo BOOTSTRAP inicial ATIVO"));
            Assert.That(initialConfigScript,Does.Contain("Resumo de status/health"));
            Assert.That(initialConfigScript,Does.Contain("Modelo de linkage ativo"));
            Assert.That(initialConfigScript,Does.Contain("Status dos serviços no momento da geração"));
            Assert.That(initialConfigScript,Does.Not.Contain("<pre>$escaped</pre>"));
            Assert.That(initialConfigScript,Does.Contain("dev-console-html.ps1"));
            Assert.That(initialConfigScript,Does.Contain("ConvertTo-DevConsoleHtmlText"));
            Assert.That(initialConfigScript,Does.Not.Contain("function ConvertTo-HtmlEncodedText"));
            Assert.That(initialConfigScript,Does.Not.Contain("function H([object]$Value)"));
            Assert.That(initialConfigScript,Does.Not.Contain("$(H "));
            Assert.That(htmlHelper,Does.Contain("function ConvertTo-DevConsoleHtmlText"));
            Assert.That(htmlHelper,Does.Contain("HtmlEncode"));
            Assert.That(htmlHelperTest,Does.Contain("57E6D8EB-42B0-49CB-8EC8-206A377B0BC5"));
            Assert.That(htmlHelperTest,Does.Contain("Get-Alias -Name h"));
            Assert.That(htmlHelperTest,Does.Contain("DEV CONSOLE HTML ENCODER / ALIAS h: OK"));
            Assert.That(infraScript,Does.Contain("dev-console-initial-config.ps1"));
            Assert.That(infraScript,Does.Contain("dev-console-contract-bundle.ps1"));
            Assert.That(infraScript,Does.Contain("Gerando bundle inicial de contratos e configurações exigido pela ingestão"));
            Assert.That(infraScript,Does.Contain("dev-console-operations.ps1"));
            Assert.That(infraScript,Does.Contain("-Action calibrate-initial"));
            Assert.That(infraScript,Does.Contain("modelo BOOTSTRAP inicial ATIVO"));
            Assert.That(infraScript,Does.Contain("Estado transitório da Console removido"));
            Assert.That(infraScript,Does.Contain("Histórico de execuções foi preservado"));
            Assert.That(localCluster,Does.Contain("[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)"));
            Assert.That(localCluster,Does.Contain("Assert-DockerEngineAvailable"));
            Assert.That(localCluster,Does.Contain("Docker Desktop/Engine não está em execução"));
            Assert.That(localCluster,Does.Contain("Etapa cluster 1/6"));
            Assert.That(localCluster,Does.Contain("Show-ComposeFailureDiagnostics"));
            Assert.That(localCluster,Does.Contain("$composeExitCode=$LASTEXITCODE"));
            Assert.That(localCluster,Does.Contain("[string]::IsNullOrWhiteSpace($bootstrapId)"));
            Assert.That(localCluster,Does.Contain("docker inspect --format '{{json .State}}' $bootstrapId"));
            Assert.That(localCluster,Does.Contain("$bootstrapExitCode=[int]$bootstrapState.ExitCode"));
            Assert.That(localCluster,Does.Contain("$bootstrapStatus=[string]$bootstrapState.Status"));
            Assert.That(localCluster,Does.Contain("init one-shot terminou com exit 0"));
            Assert.That(localCluster,Does.Contain("retorno do wrapper ignorado"));
            Assert.That(localCluster,Does.Contain("Bootstrap da referência IBGE falhou (status="));
            Assert.That(localCluster,Does.Contain("LOCAL_CLUSTER_TEST_DOSSIER"));
            Assert.That(localCluster,Does.Contain("sp_registrar_dossie_decisao_modelo_linkage"));
            Assert.That(localCluster,Does.Contain("@acao=N'VALIDATE'"));
            Assert.That(localCluster,Does.Contain("@acao=N'ACTIVATE'"));
            Assert.That(localCluster,Does.Contain("Gate DT-15 DEV preparado para VALIDATE"));
            Assert.That(localCluster,Does.Contain("Gate DT-15 DEV preparado para ACTIVATE"));
            Assert.That(localCluster,Does.Contain("Logs do jornada-reference-bootstrap"));
            Assert.That(localCluster,Does.Contain("Ensure-SyntheticIbgeIdentityText"));
            Assert.That(localCluster,Does.Contain("Pessoa Teste %"));
            Assert.That(localCluster,Does.Contain("Jornada_Dev_SyntheticScale_Diversify.sql"));
            Assert.That(localCluster,Does.Contain("nomes/nome da mãe amostrados pela frequência IBGE"));
            Assert.That(opsScript,Does.Contain("[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)"));
            Assert.That(opsScript,Does.Contain("[string[]]$ComposeArgs"));
            Assert.That(opsScript,Does.Contain("@ComposeArgs"));
            Assert.That(opsScript,Does.Contain("Invoke-Compose exige um subcomando"));
            Assert.That(opsScript,Does.Contain("'system-status'"));
            Assert.That(opsScript,Does.Contain("ESTADO GERAL: OK"));
            Assert.That(opsScript,Does.Contain("execução one-shot"));
            Assert.That(opsScript,Does.Not.Contain("[string[]]$Args"));
            Assert.That(opsScript,Does.Contain("--mode','REPLAY"));
            Assert.That(opsScript,Does.Contain("JOIN ingestao.lote l ON l.lote_id=po.lote_id"));
            Assert.That(opsScript,Does.Contain("WHERE l.entrega_id='$entregaId' AND po.cpf IS NULL"));
            Assert.That(opsScript,Does.Contain("--pessoa-observacao-id"));
            Assert.That(opsScript,Does.Contain("dev-console-entrega:$entregaId"));
            Assert.That(opsScript,Does.Contain("Backlog pendente de outras cargas não foi selecionado."));
            Assert.That(runtime,Does.Contain("somente para as observações elegíveis da última entrega enviada pela Console DEV"));
            Assert.That(runtime,Does.Contain("O backlog sintético global permanece intacto"));
            Assert.That(runtime,Does.Contain("[\"infrastructure\",\"zip\"]"));
            Assert.That(page,Does.Contain("A tela mostra somente operações reais"));
            Assert.That(page,Does.Contain("Pré-requisitos:"));
            Assert.That(page,Does.Contain("dependencyNote"));
            Assert.That(page,Does.Contain("Formulário HTML"));
            Assert.That(page,Does.Contain("JSON / JSONL"));
            Assert.That(page,Does.Contain("Atualizar exemplo da Gold"));
            Assert.That(page,Does.Contain("Visualização amigável"));
            Assert.That(page,Does.Not.Contain("Visualizar JSON em HTML"));
            Assert.That(page,Does.Contain("Arquivos gerados:"));
            Assert.That(page,Does.Contain("Consulta semicega · DEV sintético"));
            Assert.That(page,Does.Contain("Contratos de ingestão"));
            Assert.That(page,Does.Contain("Validar e salvar"));
            Assert.That(page,Does.Contain("openContractDialog()"));
            Assert.That(page,Does.Contain("Configurações JSON ativas"));
            Assert.That(page,Does.Contain("Visualização amigável"));
            Assert.That(page,Does.Contain("Arquivo fonte:"));
            Assert.That(page,Does.Contain("Runtime:"));
            Assert.That(page,Does.Contain("openActiveConfigDialog()"));
            Assert.That(page,Does.Contain("Usar exemplo da Gold sintética"));
            Assert.That(devEnv,Does.Contain("JornadaSyntheticDev"));
            Assert.That(devEnv,Does.Contain("JORNADA_LOCAL_SYNTHETIC_PEOPLE"));
            Assert.That(devEnv,Does.Contain("30000"));
            Assert.That(compose,Does.Contain("SemiblindIdentitySearch__Enabled"));
            Assert.That(compose,Does.Contain("test-access-keys.json:/opt/jornada/config/security/test-access-keys.json:ro"));
            Assert.That(compose,Does.Contain("[reference-bootstrap] Iniciando ENSURE_NAME_FREQUENCY_SNAPSHOT"));
            Assert.That(compose,Does.Not.Contain("LinkageParameters__Operation=ENSURE_IBGE_NOMINAL_U_REFERENCE dotnet"));
            Assert.That(bootstrap,Does.Contain("restore $Solution --locked-mode"));
            Assert.That(bootstrap,Does.Contain("build $Solution --no-restore"));

            var launch=File.ReadAllText(Path.Combine(root,"Solution","Jornada.slnLaunch"));
            Assert.That(launch,Does.Contain("Jornada.DevConsole.csproj"));
            Assert.That(launch,Does.Contain("\"Action\": \"Start\""));

            Assert.That(program,Does.Not.Contain("Jornada.Api"));
        });
    }
}
